### ISSUE TITLE
RCall & parallel Julia

### ISSUE THREAD

**Issue by diegozea** [JuliaInterop/RCall.jl#111]
The following gives always the same value using RCall (Is only one R process used?)

``` julia
@everywhere begin
using RCall
println("R: ", rcopy(reval("rnorm(1)")))
println("J: ", rand())
end
```

```
$ julia -p 4 ie.jl
WARNING: replacing module RCall
WARNING: replacing module RCall
WARNING: replacing module RCall
WARNING: replacing module RCall
    From worker 4:  R: -0.1163204383902153
    From worker 3:  R: -0.1163204383902153
    From worker 4:  J: 0.44353377046424947
    From worker 3:  J: 0.7043025808737526
    From worker 2:  R: -0.1163204383902153
    From worker 2:  J: 0.3554139816169426
R: -    From worker 5:  R: -0.1163204383902153
0.  From worker 5:  J: 0.18710603813521098
1163204383902153
J: 0.34294676220127096
```

**Comment by simonbyrne** [comment]
Yes, RCall does not support multiple threads, so use at your own risk!

**Comment by diegozea** [comment]
Thanks! That should be documented... I don't know about the RCall internals. RCall spawn a R process, doesn't it? Can each Julia worker start their own R process in the background?

**Comment by simonbyrne** [comment]
Yes, we should definitely document it.

We do start an R session, but it's part of the same process. I'm not
exactly sure how this would work with multiple processes.

**Comment by armgong** [comment]
IMHO,  when parallel julia ( julia -p 4 ) , it is multiple processes , so there are 4 julia process.
when execute using RCall, each julia process should  start an unique R process, the message should not appear.

right now I am coding rjulia2 (http://github.com/armgong/rjulia2 ) using RCall.jl , also need this issue to be solved, otherwise will lose parallel julia feature like rjulia1, this will be litte dispointing, and for the feature I need maintain both rjulia (have parallel feature) and rjulia2 (no parallel feature) .

if there is any thing I can help , please tell me.

**Comment by simonbyrne** [comment]
How do the parallel features of rjulia1 work?

**Comment by armgong** [comment]
https://github.com/armgong/rjulia/blob/julia0.5/demo/testParallel.R
And now some I want implement rjulia2 not only just parallel Julia but also can call r function on Julia worker process, so we can use it build a r and Julia cluster, do more than just r call Julia or Julia call r.

**Comment by armgong** [comment]
What I want is like this
'''r
Library(rjulia2)
Julia_init()
Julia_eval("addprocs(3)")
Julia_eval("@everywhere begin
using RCall end"
'''
Now we built a mesh net r and Julia, can use it do distributed work(r or julia) and every slave process

**Comment by armgong** [comment]
it isn't rcall issue , it is an upstream issue, see   https://github.com/JuliaLang/julia/issues/19187 and https://github.com/JuliaLang/julia/pull/19073 ,but  still open yet , unfortunatlly.

**Comment by armgong** [comment]
julia 0.6-rc2 seems solve this ,this issue can close now

**Comment by armgong** [comment]
~~~julia
julia> using RCall
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/armgong/.julia/v0.6/NullableArrays/src/operators.jl:128.

julia> addprocs(3)
3-element Array{Int32,1}:
 2
 3
 4

julia> @everywhere using RCall
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/armgong/.julia/v0.6/NullableArrays/src/operators.jl:128.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/armgong/.julia/v0.6/NullableArrays/src/operators.jl:128.
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /home/armgong/.julia/v0.6/NullableArrays/src/operators.jl:128.

julia> @everywhere begin varfromr=rcopy(reval("runif(3)")); println(myid(),"--",varfromr); end
1--[0.0181148, 0.517853, 0.859234]
        From worker 2:  2--[0.0126603, 0.784589, 0.720589]
        From worker 4:  4--[0.134313, 0.808572, 0.965115]
        From worker 3:  3--[0.834063, 0.374266, 0.42791]

julia> versioninfo
versioninfo (generic function with 4 methods)

julia> versioninfo()
Julia Version 0.6.0-rc2.0
Commit 68e911be53* (2017-05-18 02:31 UTC)
Platform Info:
  OS: Linux (armv7l-unknown-linux-gnueabihf)
  CPU: ARMv7 Processor rev 3 (v7l)
  WORD_SIZE: 32
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libm
  LLVM: libLLVM-3.9.1 (ORCJIT, cortex-a15)

julia>
~~~

**Comment by randy3k** [comment]
confirmed that it was fixed.
