### ISSUE TITLE
Passing DataFrame with large integer value in it throws cryptic error

### ISSUE THREAD

**Issue by davidanthoff** [JuliaInterop/RCall.jl#116]
Here is the repo:

``` julia
using DataFrames, RCall

df = DataFrame(x=[2^63 - 1, 2])

R"$df"
```

**Comment by randy3k** [comment]
It is expected due to the limitation of integer size, R has a limitation of 2^32-1. It also happens for plain julia integer `RObject(2^63 - 1)`.

You should convert the julia variables/vectors to float number/float array.

**Comment by davidanthoff** [comment]
Ah, interesting! Maybe RCall could throw a better error message that points people in the right direction if this happens?

**Comment by simonbyrne** [comment]
Maybe we could define our own `RConversionException`?

**Comment by randy3k** [comment]
we need to first investigate the time/resources required for checking integer overflow or any other conversion validity.

However, making our own exceptions is not a bad idea.
