### ISSUE TITLE
Use NamedArrays.jl to preserve array names

### ISSUE THREAD

**Issue by nalimilan** [JuliaInterop/RCall.jl#144]
`rcopy(Titanic)` currently returns a plain `DataArray`, and loses all names. It would be much better to wrap this array inside a `NamedArray`.

**Comment by randy3k** [comment]
It is an issue needed to be addressed. In the meanwhile, users could consider the following code.

```julia
using RCall
using NamedArrays

function RCall.rcopy(::Type{NamedArray}, r::RObject)
    dnames = rcall(:dimnames, r)
    isnull(dnames) && error("r has no dimnames")
    NamedArray(rcopy(Array, r), [rcopy(n) for n in dnames], rcopy(getnames(dnames)))
end

rcopy(NamedArray, R"Titanic")
```

**Comment by phaverty** [comment]
Or AxisArrays?  Has anyone done the bake-off for those two?
