### ISSUE TITLE
move to JuliaInterop?

### ISSUE THREAD

**Issue by StefanKarpinski** [JuliaInterop/RCall.jl#146]
Would it make more sense for this to live in [JuliaInterop](https://github.com/orgs/JuliaInterop)? While R is a statistical language, calling to and from R seems like it has more in common with other interop packages then with statistics packages, so there's more chance of fruitful collaboration and transfer of ideas between packages if RCall lives over there than here.

**Comment by simonbyrne** [comment]
I don't really mind either way. @randy3k and @dmbates?

**Comment by dmbates** [comment]
Fine with me.

**Comment by randy3k** [comment]
i am okay

**Comment by ararslan** [comment]
👍 Seems like a good idea to me.

**Comment by StefanKarpinski** [comment]
Any of you who have admin access to RCall should be able to do this since I've invited you to join JuliaInterop and as members you can create repos over there. Let me know if there are any issues.

**Comment by simonbyrne** [comment]
Done.

**Comment by randy3k** [comment]
@simonbyrne Somehow I lose the writing permission to the repo, could you add me back to the repo?

**Comment by simonbyrne** [comment]
You should have access now.

**Comment by randy3k** [comment]
@simonbyrne Thanks.
