### ISSUE TITLE
Plot in RCall trigger kernel dead in IJulia

### ISSUE THREAD

**Issue by egoecho** [JuliaInterop/RCall.jl#147]
In Julia 0.5, when I try to draw a plot using RCall in IJulia, the kernel will be dead. No any further error information is showed. In REPL environment, RCall runs well. And also in IJulia, run a R command without draw (such as R"date()") will work fine without any error.

**Comment by randy3k** [comment]
Is there any error message in the jupyter log file?

**Comment by randy3k** [comment]
Also, what versions of R, Julia, RCall are you using?

**Comment by egoecho** [comment]
Version:
Julia:v0.5.0; R:3.3.0; IJulia:v1.3.2; RCall:v0.5.2

I ran jupyter notebook --debug but no useful error message showed during kernel dead. I ran:

using RCall
R"plot(1:5,1:5)"

in Jupyter (IJulia), and then the kernel restarted. During that, I only got below message on jupyter terminal:

Starting kernel event loops.
[D 17:50:27.118 NotebookApp] Received kernel info: {'implementation': 'ijulia', 'bann
er': 'Julia: A fresh approach to technical computing.', 'language_info': {'mimetype':
 'application/julia', 'file_extension': '.jl', 'version': '0.5.1', 'name': 'julia'}, 
'help_links': [{'url': 'http://julialang.org/', 'text': 'Julia Home Page'}, {'url': '
http://docs.julialang.org/', 'text': 'Julia Documentation'}, {'url': 'http://pkg.juli
alang.org/', 'text': 'Julia Packages'}], 'protocol_version': '5.0'}                 
[D 17:50:27.118 NotebookApp] Opening websocket /api/kernels/6a904907-aea7-4028-8131-f
c9079af5ed5/channels                                                                
[D 17:50:27.118 NotebookApp] Connecting to: tcp://127.0.0.1:49243
[D 17:50:27.119 NotebookApp] Connecting to: tcp://127.0.0.1:37580
[D 17:50:27.119 NotebookApp] Connecting to: tcp://127.0.0.1:60588
[I 17:50:50.692 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel 6a904907-aea7-4028-8131-fc9079af5ed5 restarted
[D 17:50:50.693 NotebookApp] Starting kernel: [u'/home/jxiong/programs/julia-0.5/juli
a/usr/bin/julia', u'-i', u'--startup-file=yes', u'/home/jxiong/.julia/v0.5/IJulia/src
/kernel.jl', u'/home/jxiong/.local/share/jupyter/runtime/kernel-6a904907-aea7-4028-81
31-fc9079af5ed5.json']                                                              
[D 17:50:50.698 NotebookApp] Connecting to: tcp://127.0.0.1:47206
Starting kernel event loops.
[D 17:50:53.697 NotebookApp] KernelRestarter: restart apparently succeeded

**Comment by simonbyrne** [comment]
what's your `versioninfo()`

**Comment by egoecho** [comment]
Julia Version 0.5.1-pre+4
Commit 282f0b3* (2016-09-27 18:22 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2680 0 @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, sandybridge)

**Comment by egoecho** [comment]
Except the messages showing on terminal, is there any log file in Jupyter that could tell me the reason of crash?

**Comment by ararslan** [comment]
Previously you said that your Julia version was 0.5.0, but your `versioninfo` says 0.5.1-pre. Do you know which one is set up as the IJulia kernel you're using? That is, when you run `versioninfo` from within an IJulia notebook, is the output that you've posted?

**Comment by egoecho** [comment]
The Julia 0.5.1-pre is the one I am using. I pulled Julia source code from github, checkout to release-0.5, and then compiled it. It should be "almost" 0.5.0, I think.

**Comment by egoecho** [comment]
I cleaned LD_LIBRARY_PATH, recompiled Julia and the problem is solved :) Maybe there is something wrong in my LD_LIBRARY_PATH. Thanks everyone!
