### ISSUE TITLE
Problem with library and R""" code """-blocks

### ISSUE THREAD

**Issue by jmgnve** [JuliaInterop/RCall.jl#149]
I work on a computer without administration privileges. For loading packages I run the following piece of code and add the path to the R libraries stored in my user account:

```
using RCall
path_fig = string("some string")
R"""
library(zoo, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
library(hydroGOF, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
library(labeling, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
library(ggplot2, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
path_fig <- $path_fig
"""
```

This code produces this error:

```
ERROR: LoadError: RCall.jl: unexpected symbol
 in include at boot.jl:261
 in include_from_node1 at loading.jl:320
while loading C:\Jan_Shared\Jottacloud\Jcode\test1.jl, in expression starting on line 14
```

If I split the R""" code """-block into two blocks, the code works:

```
using RCall
path_fig = string("some string")
R"""
library(zoo, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
library(hydroGOF, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
library(labeling, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
"""
R"""
library(ggplot2, lib.loc="C:/Users/jmg/Documents/R/win-library/3.2")
path_fig <- $path_fig
"""
```

On my private computer, I don´t need the lib.loc path and everything works fine. If I add the path to the standard folder of R (`lib.loc="C:/Program Files/R/R-3.2.0/library"`) I get the same error as above.

**Comment by randy3k** [comment]
It is due to bug of using `R_ParseContextLast` to detect parse error location.
```
rparse("""
library(zoo, lib.loc="/usr/local/lib/R/3.3/site-library")
library(hydroGOF, lib.loc="/usr/local/lib/R/3.3/site-library")
library(labeling, lib.loc="/usr/local/lib/R/3.3/site-library")
library(ggplot2, lib.loc="/usr/local/lib/R/3.3/site-library")
path_fig <- \$path_fig
""")
unsafe_load(cglobal((:R_ParseContextLast, RCall.libR), Cint))
``

While I expect it returns 25x, it returns 3.

**Comment by simonbyrne** [comment]
Is this some sort of overflow in `R_ParseContextLast`?

**Comment by simonbyrne** [comment]
Looks like R uses a circular buffer:
https://github.com/wch/r-source/blob/5a4bd1b6c67b252bcdec4b7ec41119d9581d8b3e/src/include/Defn.h#L718-L721

May need to go back to the line/col method.

**Comment by randy3k** [comment]
how about dispatching the line/col approach for ascii code and `R_ParseContextLast` approach for unicode code < 256 bytes.

We could still accept unicode code > 256 bytes if it has no parse error.
