### ISSUE TITLE
High level API?

### ISSUE THREAD

**Issue by datnamer** [JuliaInterop/RCall.jl#15]
Looks like it is shaping up to be a great package. Thanks for spearheading this. 

 Are there plans for a more julian like higher level API maybe using macros?

**Comment by dmbates** [comment]
Can you expand on what you would like such an API to be?

**Comment by datnamer** [comment]
Perhaps I'm having trouble parsing the documentation owing to my lack of R experience, but I was thinking of something like this: http://rpy.sourceforge.net/rpy2/doc-2.4/html/robjects_functions.html#robjects-functions

**Comment by lgautier** [comment]
Check the `importr` here:
https://github.com/lgautier/Rif.jl/blob/master/README.md

**Comment by palday** [comment]
@datnamer  See #287 and `@rimport`:
```julia
help?> @rimport
  Import an R Package as a Julia module. For example,

  @rimport ggplot2

  is equivalent to ggplot2 = rimport("ggplot2") with error checking.

  You can also use classic Python syntax to make an alias: @rimport *package-name* as *shorthand*

  @rimport ggplot2 as gg

  which is equivalent to gg = rimport("ggplot2").
```
