### ISSUE TITLE
Fail Precompiling RCall

### ISSUE THREAD

**Issue by paragrastogi** [JuliaInterop/RCall.jl#152]
Hi all,

I'm a new Julia user so this might be a silly question. I am trying a script where I use RCall. When I run the script (either in Atom/Juno or Julia command line), I get the following error:

> ERROR: LoadError: LoadError: Could not open registry key
>  in openkey(::UInt32, ::String, ::UInt32) at C:\Users\rasto\.julia\v0.5\WinReg\src\WinReg.jl:59
>  in querykey(::UInt32, ::String, ::String) at C:\Users\rasto\.julia\v0.5\WinReg\src\WinReg.jl:112
>  in locate_rhome() at C:\Users\rasto\.julia\v0.5\RCall\src\setup.jl:8
>  in include_from_node1(::String) at .\loading.jl:488 (repeats 2 times)
>  in macro expansion; at .\none:2 [inlined]
>  in anonymous at .\<missing>:?
>  in eval(::Module, ::Any) at .\boot.jl:234
>  in process_options(::Base.JLOptions) at .\client.jl:239
>  in _start() at .\client.jl:318
> while loading C:\Users\rasto\.julia\v0.5\RCall\src\setup.jl, in expression starting on line 18
> while loading C:\Users\rasto\.julia\v0.5\RCall\src\RCall.jl, in expression starting on line 20
> ERROR: Failed to precompile RCall to C:\Users\rasto\.julia\lib\v0.5\RCall.ji.
>  in compilecache(::String) at .\loading.jl:593
>  in require(::Symbol) at .\loading.jl:422

I already installed RCall using the Pkg.add command, and that worked fine. 

I'm not sure why Julia cannot suddenly open the registry key. Actually I'm only vaguely aware of what the registry key is!

Thanks,

P

**Comment by simonbyrne** [comment]
Do you have R installed? If so, how did you install it?

**Comment by paragrastogi** [comment]
Aha! That was it 👍 . Sorry about that oversight, I'm working on a new computer!

**Comment by simonbyrne** [comment]
We should probably output a better error message here.
