### ISSUE TITLE
Examples of complex variable creation in julia, and then passed to R.

### ISSUE THREAD

**Issue by Ward9250** [JuliaInterop/RCall.jl#155]
R packages often introduce more complex custom variables/objects with an S3 or S4 class. These are sometimes lists with certain elements and then a class attribute in the case of S3, or a more formal thing (S4), say you had such a custom class in R, and a corresponding type defined in julia, can you provide an example of the methods and types one would need to define to transfer such custom classes between julia and R?

E.g.
Custom R class:

```R
a <- list("AwesomeA" = c(1,2,3,4,5), "AwesomeB" = c(TRUE, FALSE))
class(a) <- "MyAwesomeClass"
```

And the corresponding julia type
```julia
type MyAwesomeType
    AwesomeA::Vector{Int}
    AwesomeB::Vector{Bool}
end
```

**Comment by Ward9250** [comment]
Ah I've seen this is already asked #138

**Comment by ararslan** [comment]
Since this has already been asked, I'm going to go ahead and close this.
