### ISSUE TITLE
Override conversion of length-1 vectors to scalars?

### ISSUE THREAD

**Issue by dmbates** [JuliaInterop/RCall.jl#157]
I have run into a problem converting an `R` factor with only 1 level to a `CategoricalArrays.CategoricalArray`.

I do realize that having only one level for a factor makes it somewhat uninformative but these things do occur after subsetting a data frame and dropping unused levels.

Currently at line 30 of `src/convert-data.jl` the value of `levels` will be a scalar if there is only one level.  I can add code to check on whether the result is an array and, if not, make it an array but I was wondering if there is a more general idiom to override the conversion of length-1 vectors to scalars?

**Comment by randy3k** [comment]
We could do `rcopy(Array,getattrib(s,Const.LevelsSymbol))`, it also forces the return as an array.

**Comment by randy3k** [comment]
fixed, 53fb8557655bd5613db1b4bbddf5324b934a81b6
