### ISSUE TITLE
"using RCall" crashes julia on CentOS Linux

### ISSUE THREAD

**Issue by ahalwright** [JuliaInterop/RCall.jl#162]
When I do "using RCall" in julia 0.5.0 on CentOS Linux, julia crashes.

The error message is attached, and the details of my version of CentOS are at the end of the error message.

Interestingly, this does not happen on Ubuntu 16.10 or Windows, again with julia 0.5.0.

[using_RCall_error_message.txt](https://github.com/JuliaInterop/RCall.jl/files/667693/using_RCall_error_message.txt)

**Comment by ararslan** [comment]
I'm pasting your error message here so it's easier to see:
```
[wright@pardosa julia]$ julia-debug
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> using RCall
INFO: Precompiling module RCall.
ERROR: LoadError: LoadError: Library  not found.
 in validate_libR(::String) at /home/wright/.julia/v0.5/RCall/src/setup.jl:8
 in locate_Rhome_libR() at /home/wright/.julia/v0.5/RCall/src/setup.jl:120
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in macro expansion; at ./none:2 [inlined]
 in anonymous at ./<missing>:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
while loading /home/wright/.julia/v0.5/RCall/src/setup.jl, in expression starting on line 127
while loading /home/wright/.julia/v0.5/RCall/src/RCall.jl, in expression starting on line 20
ERROR: Failed to precompile RCall to /home/wright/.julia/lib/v0.5/RCall.ji.
 in compilecache(::String) at ./loading.jl:593
 in require(::Symbol) at ./loading.jl:422


[wright@pardosa julia]$ cat /proc/version
Linux version 3.10.0-327.36.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) ) #1 SMP Sun Sep 18 13:04:29 UTC 2016
```

**Comment by simonbyrne** [comment]
Do you have R installed? What does `R RHOME` at the shell give?

**Comment by ahalwright** [comment]
Yes, R is installed, and RCall has worked in the past.  Definitely with
julia version 4.


R RHOME gives /usr/lib64/R.  



Alden





On Thu, Dec 22, 2016, at 12:10, Simon Byrne wrote:

> Do you have R installed? What does R RHOME at the shell give?



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/JuliaInterop/RCall.jl/issues/162#issuecomment-268868929

**Comment by simonbyrne** [comment]
What does `Libdl.find_library(["libR"],["/usr/lib64/R/lib"])` give?

Does `/usr/lib64/R/lib/libR.so` exist?

**Comment by dmbates** [comment]
It might help to run
```
Pkg.build("RCall")
```

In theory that script should ferret out the location of `libR`

**Comment by ahalwright** [comment]
julia> Libdl.find_library(["libR"],["/usr/lib64/R/lib"])

""

$ ls -l /usr/lib64/R/lib/libR.so

-rwxr-xr-x. 1 root root 2951384 Oct 31 14:14 /usr/lib64/R/lib/libR.so*







On Thu, Dec 22, 2016, at 13:39, Simon Byrne wrote:

> What does Libdl.find_library(["libR"],["/usr/lib64/R/lib"]) give?



> Does /usr/lib64/R/lib/libR.so exist?



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/JuliaInterop/RCall.jl/issues/162#issuecomment-268885846

**Comment by ahalwright** [comment]
To summarize:  Pkg.build("RCall") succeeds but does not change
the error.




[wright@pardosa ~]$ julia

julia> Pkg.build("RCall")



julia> using RCall

INFO: Precompiling module RCall.

ERROR: LoadError: LoadError: Library  not found.

in validate_libR(::String) at
/home/wright/.julia/v0.5/RCall/src/setup.jl:8
in locate_Rhome_libR() at
/home/wright/.julia/v0.5/RCall/src/setup.jl:120
in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)

in macro expansion; at ./none:2 [inlined]

in anonymous at ./<missing>:?

in eval(::Module, ::Any) at ./boot.jl:234

in process_options(::Base.JLOptions) at ./client.jl:239

in _start() at ./client.jl:318

while loading /home/wright/.julia/v0.5/RCall/src/setup.jl, in expression
starting on line 127
while loading /home/wright/.julia/v0.5/RCall/src/RCall.jl, in expression
starting on line 20
ERROR: Failed to precompile RCall to /home/wright/.julia/lib/v0.5/RCall.ji.
in compilecache(::String) at ./loading.jl:593

in require(::Symbol) at ./loading.jl:422







On Thu, Dec 22, 2016, at 14:10, Douglas Bates wrote:

> It might help to run


> Pkg.build("RCall")
> 

> In theory that script should ferret out the location of libR



> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/JuliaInterop/RCall.jl/issues/162#issuecomment-268891159

**Comment by simonbyrne** [comment]
Okay, two more: in Julia:
```
Libdl.dlopen("/usr/lib64/R/lib/libR.so")
```

and at the shell:
```
ldd /usr/lib64/R/lib/libR.so
```

**Comment by ahalwright** [comment]
julia> Libdl.dlopen("/usr/lib64/R/lib/libR.so")

ERROR: could not load library "/usr/lib64/R/lib/libR.so"

libRblas.so: cannot open shared object file: No such file or directory

in dlopen(::String, ::UInt32) at ./libdl.jl:90 (repeats 2 times)



[wright@pardosa ~]$ ls /usr/lib64/R/lib/

libopenblas.so.0@  libRblas.so@  libRlapack.so*  libRrefblas.so*
libR.so*


[wright@pardosa ~]$ ldd /usr/lib64/R/lib/libR.so

        linux-vdso.so.1 =>  (0x00007ffe133e3000)

        libRblas.so => not found

        libgfortran.so.3 => /lib64/libgfortran.so.3 (0x00007f9b3c874000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f9b3c572000)

        libquadmath.so.0 => /lib64/libquadmath.so.0 (0x00007f9b3c336000)
        libreadline.so.6 => /lib64/libreadline.so.6 (0x00007f9b3c0ef000)
        libtre.so.5 => /lib64/libtre.so.5 (0x00007f9b3bedf000)

        libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f9b3bc7e000)

        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f9b3ba57000)

        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f9b3b847000)

        libz.so.1 => /lib64/libz.so.1 (0x00007f9b3b631000)

        librt.so.1 => /lib64/librt.so.1 (0x00007f9b3b428000)

        libdl.so.2 => /lib64/libdl.so.2 (0x00007f9b3b224000)

        libicuuc.so.50 => /lib64/libicuuc.so.50 (0x00007f9b3aeab000)

        libicui18n.so.50 => /lib64/libicui18n.so.50 (0x00007f9b3aaab000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00007f9b3a885000)

        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9b3a669000)

        libc.so.6 => /lib64/libc.so.6 (0x00007f9b3a2a7000)

        /lib64/ld-linux-x86-64.so.2 (0x00007f9b3d1ce000)

        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9b3a091000)

        libtinfo.so.5 => /lib64/libtinfo.so.5 (0x00007f9b39e67000)

        libicudata.so.50 => /lib64/libicudata.so.50 (0x00007f9b38892000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9b38589000)







On Fri, Dec 23, 2016, at 00:52, Simon Byrne wrote:

> Okay, two more: in Julia:


> Libdl.dlopen("/usr/lib64/R/lib/libR.so")
>
> and at the shell:


> ldd /usr/lib64/R/lib/libR.so
> 

> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/JuliaInterop/RCall.jl/issues/162#issuecomment-268952768

**Comment by dmbates** [comment]
@ahalwright try `ls -l /usr/lib64/R/lib/`

It appears that `/usr/lib64/R/lib/libRblas.so` is a symbolic link to a file that may not exist.

**Comment by ahalwright** [comment]
The file does exist after following two symbolic links. 



[wright@pardosa ~]$ ls -l /usr/lib64/R/lib/

total 5080

lrwxrwxrwx. 1 root root      11 Dec 13 07:37 libopenblas.so.0 ->
libRblas.so*
lrwxrwxrwx. 1 root root      27 Dec 13 07:37 libRblas.so ->
/usr/lib64/libopenblas.so.0*
-rwxr-xr-x. 1 root root 2063928 Oct 31 14:14 libRlapack.so*

-rwxr-xr-x. 1 root root  183800 Oct 31 14:14 libRrefblas.so*

-rwxr-xr-x. 1 root root 2951384 Oct 31 14:14 libR.so*



[wright@pardosa ~]$ ls -l /usr/lib64/libopenblas.so.0

lrwxrwxrwx. 1 root root 22 Dec 13 07:33 /usr/lib64/libopenblas.so.0 ->
libopenblas-r0.2.19.so*


[wright@pardosa ~]$ ls -l /usr/lib64/libopenblas-r0.2.19.so

-rwxr-xr-x. 1 root root 33947648 Nov  3 14:34 /usr/lib64/libopenblas-
r0.2.19.so*








On Fri, Dec 23, 2016, at 11:23, Douglas Bates wrote:

> @ahalwright[1] try ls -l /usr/lib64/R/lib/



> It appears that /usr/lib64/R/lib/libRblas.so is a symbolic link to a
> file that may not exist.
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 




Links:

  1. https://github.com/ahalwright
  2. https://github.com/JuliaInterop/RCall.jl/issues/162#issuecomment-269028024

**Comment by simonbyrne** [comment]
Okay, try adding `/usr/lib64/R/lib/` to your `LD_LIBRARY_PATH`, I think that should fix it. I'll try to make it so that it throws a more informative error.

Just so I know, what version of CentOS are you using, and how did you install R?

**Comment by ahalwright** [comment]
Yes, this fixes the problem.  Thank you for your help.



[wright@pardosa ~]$ uname -r

3.10.0-327.36.1.el7.x86_64

[wright@pardosa ~]$ cat /etc/system-release

CentOS Linux release 7.3.1611 (Core)



I installed R from the epel respository.



Alden





On Fri, Dec 23, 2016, at 14:55, Simon Byrne wrote:

> Okay, try adding /usr/lib64/R/lib/ to your LD_LIBRARY_PATH, I think
> that should fix it. I'll try to make it so that it throws a more
> informative error.
> Just so I know, what version of CentOS are you using, and how did you
> install R?
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/JuliaInterop/RCall.jl/issues/162#issuecomment-269049809

**Comment by simonbyrne** [comment]
I've updated this so it now throws a more informative error:
```
INFO: Precompiling module RCall.
ERROR: LoadError: LoadError: Could not load library /usr/lib64/R/lib/libR.so. Try adding /usr/lib64/R/lib to the "LD_LIBRARY_PATH" environmental variable and restarting Julia.
```
Unfortunately, there's not much we can do.
