### ISSUE TITLE
There is no method sexp for `SubDataFrame`

### ISSUE THREAD

**Issue by diegozea** [JuliaInterop/RCall.jl#167]
`MethodError: no method matching sexp(::DataFrames.SubDataFrame{Array{Int64,1}})`

I got this trying to use a R function (`lm()`) inside `DataFrames.by()`.

Best,

**Comment by dmbates** [comment]
Are you planning to create a pull request?  My guess is that it may be as simple as changing a `DataFrame` signature to `Union{DataFrame,SubDataFrame}` but I haven't looked at it.

**Comment by diegozea** [comment]
I changed the signature to ` sexp(d::AbstractDataFrame)` but I got: `ERROR: type SubDataFrame has no field colindex`. Is there a reason to use `d.colindex.names` insteda of `names(d)`?

**Comment by randy3k** [comment]
It should be handled by the latest commits.
