### ISSUE TITLE
Changes for julia v0.6

### ISSUE THREAD

**Issue by dmbates** [JuliaInterop/RCall.jl#171]
I started a '0.6' branch and committed changes to fix warnings related to `abstract` and `typealias`.  At present changing the REPL prompt to `R>` does not work.  I think either @randy3k or @simonbyrne would have a better chance of fixing that than I would.

**Comment by randy3k** [comment]
The REPL bug is due to https://github.com/JuliaLang/julia/issues/19774, it seems that there is no clean fix for now.

**Comment by randy3k** [comment]
I have pushed a [PR][1] to julia and it should fix the bug in REPL model.

[1]: https://github.com/JuliaLang/julia/pull/21027

**Comment by randy3k** [comment]
I have pushed more commits to `0.6` branch. I found that it is quite tedious to make the changes backward compatible, perhaps it is more efficient and costs less labor to restrict the next minor release `julia 0.6` only.

**Comment by randy3k** [comment]
The `master` should work on both v0.5 and v0.6 now except that the REPL mode on v0.6 requires a [patch][1] at julia upstream. Let's keep this issue until the patch is merged.

[1]: https://github.com/JuliaLang/julia/pull/21027

**Comment by randy3k** [comment]
https://github.com/JuliaLang/julia/pull/21027 has merged.
