### ISSUE TITLE
DataFrames and DataTables support

### ISSUE THREAD

**Issue by nalimilan** [JuliaInterop/RCall.jl#174]
In https://github.com/JuliaInterop/RCall.jl/pull/145 RCall was changed to create `NullableArray` and `CategoricalArray` objects rather than `DataArray` and `PooledDataArray`. This was consistent with the DataFrames plans at the time.

This decision probably needs revisiting now that the plans have changed (i.e. DataFrames will keep using `DataArray` and `PooledDataArray`, and the new DataTables package uses  `NullableArray` and `CategoricalArray`). The current state is inconsistent since `DataFrame` is not made to work well with `NullableArray` and `CategoricalArray`. So there are two options:
- keep creating `DataFrame` objects by default, and go back to creating `DataArray` and `PooledDataArray` columns
- switch to `DataTable` and keep creating `NullableArray` and `CategoricalArray` columns

I'm really torn about which solution is better. We don't have all the high-level query APIs yet to make working with DataTables as nice as it should be. Yet, going back to `DataArray` could be annoying for users who already had to adapt their code. Maybe we should do it nevertheless until the `Nullable` API stabilizes, to avoid having our data frame/table ecosystem too inconsistent or painful to use for several months.

**Comment by dmbates** [comment]
@nalimilan I support the idea of going back to `DataArrays` and `PooledDataArrays` in `RCall` for the short term.  I think it would be much less confusing to make the switch to `CategoricalArrays`, `NullableArrays`, `DataTables` and `StatsModels` in one step.

When I am teaching courses for to R users by far the simplest approach is to use R to load the data and then use `RCall` to transfer.

@randy3k, @simonbyrne Let me know if I can help, should you decide that this is a good path forward.

**Comment by randy3k** [comment]
I also agree that we should switch back to `DataArrays`. In fact, I am working on the idea that I am @simonbyrne discussed earlier at https://github.com/JuliaInterop/RCall.jl/issues/138#issuecomment-264959440. Once it is done, there are converters like, `covert(DataFrame, foobar)` and `covert(DataTable, foobar)` and the default converter `rcopy`. I am thinking also some kind of register to allow users to choose their preferred default converter.

**Comment by nalimilan** [comment]
OK, let's go back to DataArrays then.
