### ISSUE TITLE
Both DataFrames and RCall export "isna"

### ISSUE THREAD

**Issue by masiddique** [JuliaInterop/RCall.jl#179]
Hi

I noticed this warning in my computations:

> WARNING: both DataFrames and RCall export "isna"; uses of it in module Main must be qualified

Is there a way to avoid this conflict?

**Comment by randy3k** [comment]
Oh, actually DataArrays has deprecated the usage of `isna(a::AbstractArray)` in favour of `broadcast` https://github.com/JuliaStats/DataArrays.jl/pull/243

I guess we should follow similar modifications.

**Comment by randy3k** [comment]
It is a bit tricky for R vector to use `broadcast` since scalar in R is just a vector of length 1.
