### ISSUE TITLE
change the size of plots

### ISSUE THREAD

**Issue by gdkrmr** [JuliaInterop/RCall.jl#180]
is there a way to change the size of plots in jupyter notebooks?

**Comment by randy3k** [comment]
It is not documented by it can be done by

```
R"""
options(device = function(filename=getOption('rcalljl_filename'),...) png(filename, width=500, height=300, ...))
plot(1:10)
"""
```

**Comment by randy3k** [comment]
Oh, I just realized that it is there
```
RCall.IJuliaHooks.ijulia_setdevice(MIME("image/png"),width=6*72,height=5*72)
# or this, if you are using an earlier version 
RCall.ijulia_setdevice(MIME("image/png"),width=6*72,height=5*72)
```

PS: also note that this is a bug in v0.7.0 preventing IJulia to be loaded. A newer version v0.7.1 has been submitted to fix it.

**Comment by gdkrmr** [comment]
the first one works, thx!!!

**Comment by randy3k** [comment]
Since 4fb43c3c69d1516f26b8d67ae4b5021260278194, the device size can be set by
```
RCall.ijulia_setdevice(MIME("image/png"),width=6*72,height=5*72)
```
