### ISSUE TITLE
Using RCall in test suites

### ISSUE THREAD

**Issue by richardreeve** [JuliaInterop/RCall.jl#185]
I'm trying to use RCall to do testing of a package by cross-checking it against an R package we have also written. However, I can't get travis or appveyor to install the packages so I can run the tests. The code I have is in [pkg_RCall.jl](https://github.com/richardreeve/Diversity.jl/blob/R/test/pkg_RCall.jl), but the critical bit is here:

```julia
using RCall

libdir = mktempdir()
@rput libdir
R".libPaths(libdir)";
R"install.packages('devtools', repos='http://cran.r-project.org', lib=libdir)";
R"devtools::install_github('boydorr/rdiversity', lib=libdir)";
R"library(rdiversity, lib.loc=c(libdir, .libPaths()))";
```

No matter how many ways I've tried to do this, I've never succeeded (it now doesn't stop with an interactive query, which it did when I didn't set the library directory, but instead it just crashes), though it always succeeded on my laptop when I run it interactively... does anyone have any suggestions?

PS The [crash log](https://travis-ci.org/richardreeve/Diversity.jl/jobs/220368837) ends with:

```
* DONE (devtools)
signal (11): Segmentation fault
while loading /home/travis/.julia/v0.5/Diversity/test/pkg_RCall.jl, in expression starting on line 11
```

**Comment by randy3k** [comment]
Can you test against the master branch? There was a similar report and the issue should have been fixed.

**Comment by richardreeve** [comment]
I just tried it with v0.7.2, which had just appeared and is level with master. The segfault no longer happens when installing packages, but `install_github()` fails when it tries to pull in other packages - it complains about a missing `GITHUB_PAT` even though the repository I'm trying to install is public. I've found a workaround, which is to manually install all of the dependencies before I install my package:

```julia
libdir = mktempdir();
rcall(Symbol(".libPaths"), libdir);
rcall(Symbol("install.packages"),
      ["devtools", "methods", "ggplot2", "ape",
       "phangorn", "tidyr", "tibble", "phytools", "reshape2"],
      repos="http://cran.r-project.org", lib=libdir);
@rput libdir
R"library(devtools, lib.loc=c(libdir, .libPaths()))";
rcall(Symbol("install_git"), "https://github.com/boydorr/rdiversity.git",
      lib=libdir);
R"library(rdiversity, lib.loc=c(libdir, .libPaths()))";
```

But this seems to be a specific issue with RCall, since it doesn't happen in R.

**Comment by randy3k** [comment]
It is because 

> GitHub rate limits API access to 5000 requests per hour 

https://www.r-bloggers.com/using-travis-make-sure-you-use-a-github-pat/amp/

**Comment by richardreeve** [comment]
Ah, okay - thanks. I didn't realised that you could create a PAT with no permissions!
