### ISSUE TITLE
Dataframe dates lost in translation

### ISSUE THREAD

**Issue by swt30** [JuliaInterop/RCall.jl#186]
```
R> df = data.frame(dates = as.Date(c("2017-04-14", "2014-04-17")))

julia> R"df"
RCall.RObject{RCall.VecSxp}
       dates
1 2017-04-14
2 2014-04-17


julia> dump(rcopy(R"df"))
DataFrames.DataFrame  2 observations of 1 variables
  dates: DataArrays.DataArray{Float64,1}(2) [17270.0,16177.0]
```

Looks like rcopy is missing the class info from the data frame and so just copying the underlying Float64 rather than using the Date conversion?

**Comment by dmbates** [comment]
What would be needed is to determine the internal structure of `dates` in `R` then create the appropriate copy method for `RCall`.  The date object in R is just a floating point array with some metadata in the attributes list.

**Comment by randy3k** [comment]
Date vectors in R are just floating point vectors. Currently, the default `rcopy(R"df$dates")` [method][1] will dispatch the call
`rcopy(Array{Date}, R"df$dates")` if the vector has "date" class attributes. However, it seems that a similar logic is missing when converting a data.frame to DataFrame.

[1]: https://github.com/JuliaInterop/RCall.jl/blob/ef772559eff29bcd04f2a6caab417b06de470304/src/convert/default.jl#L46

**Comment by randy3k** [comment]
20210c92d04cbfd14f99607948c7e306bbb087b8 should fix it.
