### ISSUE TITLE
Send bits to R as a RawSxp

### ISSUE THREAD

**Issue by Ward9250** [JuliaInterop/RCall.jl#193]
I want to compose a julia vector of a custom julia bitstype (8) or even a vector of UInt8, and then use @rput or similar to send that array to R, such that is is an R `raw` vector class, how is it possible to do this? Sending BitArrays and so on just send over Logical vectors, not raws.

**Comment by Ward9250** [comment]
The only way I've thought of doing this so far is to create the raw vector on the R side so it is in julia as a RObject, something like:
```julia
v = Vector{UInt8}(10)
r = R"raw(10)"
for i in 1:10
r[i] = v[i]
end
```

I imagine I need to do some `protect` and `unprotect`.

**Comment by randy3k** [comment]
@Ward9250 

Your code should work and `protect` and `unprotected` are not required here since the memory is created in R and referenced in the R global environment.

In long term, we should also support RawSxp.
