### ISSUE TITLE
Request for comment - rcopy for DNA sequences

### ISSUE THREAD

**Issue by Ward9250** [JuliaInterop/RCall.jl#194]
Hi,

I've written a draft rcopy method that will let the user move DNA sequences in the "DNAbin" format in R, over to the julia session as a Vector{BioSequence{DNAAlphabet{4}}} - I just wanted to post it here for comments to make sure I understand RCall.

```julia
using BioSequences
using RCall
using RCall: rcall_p, isObject, isS4, RClass, RawSxp, protect, unprotect
import RCall: rcopy, rcopytype, sexp
using Twiddle: swapbits # NEEDS TWIDDLE MASTER NOT RELEASE

function rcopy(::Type{Vector{BioSequence{DNAAlphabet{4}}}}, rs::Ptr{RawSxp})
    # protect the RawSxp from GC.
    protect(rs)

    # Check if RawSxp is a DNAbin object from APE.
    if !isObject(rs) || isS4(rs) || rcopy(RCall.rcall_p(:class, rs)) != "DNAbin"
        error("Object is not of S3 class DNAbin, aborting")
    end

    #Get some information about the object, namely the rows and cols.
    seqLen = rcopy(RCall.rcall_p(:ncol, rs))
    nSeq = rcopy(RCall.rcall_p(:nrow, rs))

    # Initialize the output vector of biological sequences.
    seqs = Vector{BioSequence{DNAAlphabet{4}}}(nSeq)
    for i in 1:nSeq
        seqs[i] = BioSequence{DNAAlphabet{4}}(seqLen)
    end

    # Fill output sequences, with data from rs.
    @inbounds for i ∈ 1:nSeq, j ∈ 1:seqLen
        seqs[i][j] = swapbits(rs[i, j] >> 4, 0, 3)
    end

    # We no longer need to work with rs, stop protecting it from GC.
    unprotect(1)
    return seqs
end

@inline function rcopytype(::Type{RClass{:DNAbin}}, s::Ptr{RawSxp})
    return Vector{BioSequence{DNAAlphabet{4}}}
end
```

In particular I was unsure about using protect and unprotect, I think as `rs`is a Ptr{RawSxp} this is appropriate if doing considerable work with `Ptr` to a `Sxp`, from what I can see of the RCall source anything that does considerable work with such pointers protects them, or if making a RObject from them, protects them until the finaliser is called. So am I right to protect? If not, why is this?

This code seems to work when I test it in my terminal:

```julia
R> library(ape)
R> a <- read.dna("Desktop/PITG_06432.fasta", format = "fasta")
R> a
6 DNA sequences in binary format stored in a matrix.

All sequences of same length: 513 

Labels:
T30-4
3928A
88069
110059
110153
EC1-C7

Base composition:
    a     c     g     t 
0.292 0.214 0.277 0.217 
julia> @rget a
6-element Array{BioSequences.BioSequence{BioSequences.DNAAlphabet{4}},1}:
 ATGGGCTTAATGCACCGACTATTGCTGCTTGCGACGTTA…GCAAGCGAACTCGATATTGACAAGTTGGAGGGGCTGTGA
 ATGGGCTTAATGCACCGACTATTGCTGCTTGCGACGTTA…GCAAGCGAACTCGATATTGACAAGTTGGAGGGGCTGTGA
 ATGGGCTTAATGCACCGACTATTGCTGCTTGCGACGTTA…GCAAGCGAACTCGATATTGACAAGTTGGAGGGGCTGTGA
 ATGGGCTTAATGCACCGACTATTGCTGCTTGCGACGTTA…GCAAGCGAACTCGATATTGACAAGTTGGAGGGGCTGTGA
 ATGGGCTTAATGCACCGACTATTGCTGCTTGCGACGTTA…GCAAGCGAACTCGATATTGACAAGTTGGAGGGGCTGTGA
 ATGGGCTTAATGCACCGACTATTGCTGCTTGCGACGTTA…GCAAGCGAACTCGATATTGACAAGTTGGAGGGGCTGTGA
```

Once I have this right, I will try going in the julia -> direction.

Thanks,
Ben.

**Comment by randy3k** [comment]
Ya, it looks right.

**Comment by randy3k** [comment]
By the way, is `seqs[i]` an array of UTF8? `unsafe_copy!` may be a bit more effecient.

**Comment by Ward9250** [comment]
@randy3k Thanks! I've nearly finished with a julia -> R sexp for the opposite conversion. 

So I'm absolutely ok to use protect and unprotect in my rcopy? Because I notice some things from RCall source that made me unsure: 

First I noticed `@rget` does getindex on RCall.Const.GlobalEnv, which yields an RObject. Also results from `R_str` return RObjects.

Second I noticed that, `rcopy` on a RObject, just calls `rcopy` on the `Ptr{Sxp}` the RObject is holding.
Since I know that the RObject has already been protected that Ptr{Sxp} for the lifetime of the RObject, when my `rcopy` method above accepts a Ptr{RawSxp} that came from an RObject, is it not already protected from GC until the RObject goes out of scope? If so, does this not make my calls to protect and unprotect basically pointless? Or is it better to have those protect and unprotect calls there, incase the Ptr{RawSxp} did not come from an RObject that has already protected it?

**Comment by randy3k** [comment]
You are correct that sometimes `protect` and `unprotect` may not be necessary. RCall tries to make sure that all the user facing functions convert the outputs to RObjects (hence protected from the GC). However, there could be edge cases that the objects may not be protected internally. It is much safer to use them rather than waiting for an expected segfault. Performance-wise, `protect` and `unprotect` are relatively cheap to use, it should not hurt the computer time.

**Comment by Ward9250** [comment]
Thanks for your comments @randy3k! I've uploaded a draft package that currently, lets DNA sequences be transferred from R (ape package) <-> julia (BioSequences/BioSymbols). I wondered if you knew about an issue I'm having with travis? I use RCall's example, to download R in the before_install section of my travis.yml file. But I'm having trouble installing the 'ape' package: my current effort is:

```
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false
before_install:
    # linux
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq -y; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install git r-base r-base-dev r-recommended -y; fi

    # osx
    # faster than using homebrew/science tap
    # but no permalink to release download
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget "https://cran.rstudio.com/bin/macosx/$(wget -qO- https://cran.rstudio.com/bin/macosx/ | sed -n 's/.*href="\(R-[^"]*.pkg\)".*/\1/p' | head -n 1)"; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo installer -pkg R-*.pkg -target /; fi

    # Set R to use local library.
    - mkdir -p mkdir $HOME/R/library
    - echo 'R_LIBS_USER="~/R/library"' >  $HOME/.Renviron
    # Set R to use R-Studio's CRAN mirror.
    - echo 'options(repos=structure(c(CRAN="https://cloud.r-project.org/")))' > .Rprofile
    # Install ape.
    - Rscript -e 'install.packages("ape")'
after_success:
  - julia -e 'cd(Pkg.dir("BioBridgeR")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("BioBridgeR")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
```

**Comment by randy3k** [comment]
Glad that you figured it out.

Btw, I just have a quick skim at your package. At the rcopy functions [here](https://github.com/BioJulia/BioBridgeR.jl/blob/2d6d45b9d57a5f8abd699b10e62a16b63c3990a7/src/ape/dnabin.jl#L166) and other locations, it is better to execute `check_class` first, then the line `protect(...)` to avoid imbalance protect/unprotect stack (i.e., the line `unprotect(...)` never got run when "check class" fails.)

**Comment by randy3k** [comment]
I also note that you may have forgotten to define `sexp(foo::Type{Foo}) = sexp(RawSxp, foo)`.
This enables to use of `@rput foo` and `RObject(foo)`.

**Comment by Ward9250** [comment]
:+1: Thanks for the heads up randy3k, I will make those changes now before 0.1 release!

**Comment by randy3k** [comment]
Let me close it now.
