### ISSUE TITLE
Ambiguity in rcopy

### ISSUE THREAD

**Issue by masiddique** [JuliaInterop/RCall.jl#195]
rcopy is not able copy the contents of an RObject due to ambiguity in function calls. 

Example:
`b = rcopy(a)`

where `a` is `RCall.RObject{RCall.VecSxp}`. I'm using v 0.7.3

Back trace is as shown below:

`MethodError: RCall.rcopy(::Type{Any}, ::Ptr{RCall.NilSxp}) is ambiguous. Candidates:
  rcopy(::Type{T}, ::Ptr{RCall.NilSxp}) where T in RCall at /home/adnan/.julia/v0.6/RCall/src/convert/base.jl:34
  rcopy(::Type{Any}, s::Ptr{S}) where S<:RCall.Sxp in RCall at /home/adnan/.julia/v0.6/RCall/src/convert/base.jl:31
Possible fix, define
  rcopy(::Type{Any}, ::Ptr{RCall.NilSxp})
copy!(::Array{Any,1}, ::Base.Generator{Ptr{RCall.VecSxp},RCall.##22#24{Any}}) at abstractarray.jl:572
rcopy(::Type{Array{Any,N} where N}, ::Ptr{RCall.VecSxp}) at base.jl:50
#rcopy#70(::Array{Any,1}, ::Function, ::Ptr{RCall.VecSxp}) at default.jl:15
#rcopy#69(::Array{Any,1}, ::Function, ::RCall.RObject{RCall.VecSxp}) at default.jl:6
rcopy(::RCall.RObject{RCall.VecSxp}) at default.jl:6
include_string(::String, ::String) at loading.jl:515
eval(::Module, ::Any) at boot.jl:235
(::Atom.##61#64)() at eval.jl:102
withpath(::Atom.##61#64, ::Void) at utils.jl:30
withpath(::Function, ::Void) at eval.jl:38
macro expansion at eval.jl:101 [inlined]
(::Atom.##60#63{Dict{String,Any}})() at task.jl:80
`

**Comment by masiddique** [comment]
Removing the function call definition `rcopy(::Type{T}, ::Ptr{RCall.NilSxp})` in **line 34, base.jl** solves the problem.

To my understanding, this happens because `NilSxp` is a subset of `Sxp`. Therefore, definitions on line 31 and 34 become ambiguous.

**Comment by randy3k** [comment]
Thanks for bringing it up.
