### ISSUE TITLE
Setup complains about R installation instead of R shared library

### ISSUE THREAD

**Issue by jasoncpatton** [JuliaInterop/RCall.jl#198]
https://github.com/JuliaInterop/RCall.jl/blob/0b45b5d5e8c2955775b10df3c323e1f10fa3b189/src/setup.jl#L121

I came across this error ("Could not find R installation. . . .") when troubleshooting for a user on our high throughput cluster. Users on our cluster have to build (and "bring") their own R installations, and R's configure script does not build the R shared library by default. This error was confusing for our user because their R installation seemed to work fine and their `PATH` and `R_HOME` were set correctly. If anyone else comes across this problem, the solution was to rebuild the R installation with `--enable-R-shlib` and to add `$R_HOME/lib` to the `LD_LIBRARY_PATH`.

Please consider splitting off the checking of validity of `libR` and `Rhome` so that you may output a more precise error. I'll try to find some time to do this myself and submit a pull request.

**Comment by randy3k** [comment]
I think you are right. Your PR will be welcome.

**Comment by randy3k** [comment]
closed by 9c8598845097a787bf3b5230fab897264d52a1d1
