### ISSUE TITLE
Could not find R installation when using Travis CI

### ISSUE THREAD

**Issue by Non-Contradiction** [JuliaInterop/RCall.jl#199]
After I install `R` and `Julia` and `RCall.jl` on Ubuntu 14.04 on Travis CI. I met the following problem in using RCall:

ERROR: LoadError: LoadError: Could not find R installation. Either set the "R_HOME" environmental variable, or ensure the R executable is available in "PATH".
 in locate_Rhome_libR() at /home/travis/.julia/v0.5/RCall/src/setup.jl:121

R executable is actually available in "PATH", and I also set `LD_LIBRARY_PATH` by `export LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH`, and `LD_LIBRARY_PATH` becomes "/home/travis/R-bin/lib/R/lib:/home/travis/R-bin/lib:".

I install R on Travis CI by setting "language": "r" in .travis.yml and I install julia by downloading julia generic linux binaries and add julia bin to path.

The detail information can be found here:
<https://travis-ci.org/Non-Contradiction/JuliaCall/jobs/261341414>

**Comment by Non-Contradiction** [comment]
When I try to print out more information, I get the following result. It seems that `libR` is not located in the place `RCall` trying to find, although Rhome is set correctly. I will check the settings further.

$ julia -e 'Rhome = readchomp(`R RHOME`); libR = joinpath(Rhome,"lib","libR.$(Libdl.dlext)"); println(Rhome); println(isdir(Rhome)); println(libR); println(isfile(libR)); println(Libdl.dlopen_e(libR))'
/home/travis/R-bin/lib/R
true
/home/travis/R-bin/lib/R/lib/libR.so
false
Ptr{Void} @0x0000000000000000

**Comment by Non-Contradiction** [comment]
R needs to build with --enable-R-shlib, and R comes with `language: r` on travis doesn't build with this.... Still looking for someway to do that...

**Comment by simonbyrne** [comment]
You can probably copy the travis.yml file from this repo.

**Comment by Non-Contradiction** [comment]
@simonbyrne Thank you very much. Using the travis.yml here (almost) solves the problem. I'm developing an R package, using `language: r` saves a lot of work installing latex and things like that which R CMD check needs. Anyway, I can do these settings in travis.yml myself.

**Comment by simonbyrne** [comment]
You could try keeping the language as R, but copy the manual steps I use to get the latest R version:
https://github.com/JuliaInterop/RCall.jl/blob/0b45b5d5e8c2955775b10df3c323e1f10fa3b189/.travis.yml#L18-L22

**Comment by Non-Contradiction** [comment]
@simonbyrne The same error appears again if I keep the language as R and use these steps to install R manually.
