### ISSUE TITLE
Error thrown by R function write.xlsx {xlsx}

### ISSUE THREAD

**Issue by giannilmbd** [JuliaInterop/RCall.jl#200]
Hi,
There seem to be a problem trying to write an xlsx file using "write.xlsx".

Here is what happens
`
using RCall

R"library('xlsx')"
RCall.jl: Loading required package: rJava

R"write.xlsx(1,'test.xlsx')"
RCall.jl: Error in write.xlsx(1, "test.xlsx") : `

Same error if I try to write a dataframe object (instead of a simple number)

Also, it doesn't really seem that the library has been loaded
`
R"?write.xlsx"
RCall.RObject{RCall.StrSxp}
No documentation for ‘write.xlsx’ in specified packages and libraries:
you could try ‘??write.xlsx’`

Best,
Gianni

**Comment by randy3k** [comment]
Did you install `xlsx` properly? Are there error messages when the package `xlsx` is loaded?
For some unknown reasons, I got segfault when it was loaded

```
R> library('xlsx')

signal (11): Segmentation fault: 11
while loading no file, in expression starting on line 0
unknown function (ip: 0x128a5b2b3)
Allocations: 7707900 (Pool: 7706482; Big: 1418); GC: 9
Loading required package: rJava
Loading required package: xlsxjars
```

**Comment by giannilmbd** [comment]
No error messages by loading. Within R it works properly.
> library('xlsx')
Loading required package: rJava
Loading required package: xlsxjars

**Comment by randy3k** [comment]
May be instead of `xlsx`, you should try [openxlsx](https://cran.r-project.org/web/packages/openxlsx/index.html). It is much lightweight and it runs faster.

**Comment by randy3k** [comment]
I suspect that xlsx has some PATH issue when it is loaded by Julia. It may be hard to figure out what the exact cause is.

**Comment by giannilmbd** [comment]
Thanks. Sounds good.
I'll try that!
Cheers
