### ISSUE TITLE
When using RCall from Julia embedded in R, things like R REPL mode are not set up.

### ISSUE THREAD

**Issue by Non-Contradiction** [JuliaInterop/RCall.jl#201]
I'm currently developing an R package JuliaCall which aims at embedding julia in R. <https://github.com/Non-Contradiction/JuliaCall>

And in the __init__() function of setup.jl of RCall, there is something like this:

    if !Rinited
       ...................
        # R gui eventloop
        isinteractive() && rgui_init()
        # R REPL mode
        isdefined(Base, :active_repl) &&
            isinteractive() && typeof(Base.active_repl) != Base.REPL.BasicREPL &&
                RPrompt.repl_init(Base.active_repl)
    end

Since julia is already embedded in R, `Rinited` is true, and the code for REPL mode will not be executed. So if I want to use R REPL mode provided by RCall, I have to  `RCall.RPrompt.repl_init(Base.active_repl)` myself like this:

![](https://non-contradiction.github.io/JuliaCall/articles/RCall.png)

Is there any reason for not doing `rgui_init()` and setting REPL mode when R is already started besides not doing repetitive work? Could we use other ways to check whether R REPL mode is set and `gui_init()` has been done?

**Comment by randy3k** [comment]
You are probably correct. Would you submit the PR?

**Comment by Non-Contradiction** [comment]
Yes, I' m going to submit a PR, although I'm not quite familiar with the julia workflow of developing packages.

**Comment by Non-Contradiction** [comment]
Sorry the screenshot is not complete. `julia_setup()` needs to use first to do some setup like this:

    library(JuliaCall)
    julia <- julia_setup()
    julia_console()

**Comment by randy3k** [comment]
I figured it out. Amazing package.

**Comment by randy3k** [comment]
I also realized I could embedde julia in an R session embedded in julia.

```julia
julia> using RCall
WARNING: Method definition ==(Base.Nullable{S}, Base.Nullable{T}) in module Base at nullable.jl:238 overwritten in module NullableArrays at /Users/Randy/.julia/v0.6/NullableArrays/src/operators.jl:99.

julia> R"library(JuliaCall); julia_setup(); julia_console()"
WARNING: RCall.jl: Julia at location /Applications/Julia-0.6.app/Contents/Resources/julia/bin will be used.
Julia version 0.6.0 found.
Julia initiation...
Finish Julia initiation.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia>
```

Though, arguably, it is useless.

**Comment by randy3k** [comment]
I reckon that we could use
```
any(:prompt in fieldnames(m) && m.prompt == "R> " for m in mirepl.interface.modes)
```
to check if the repl has been initilaized.

**Comment by Non-Contradiction** [comment]
Yes, it works. Although it seems that I need to do more work on the `JuliaCall` side. In my test, `using RCall` in `julia_console()` won't trigger `RCall.__init__()`, which is kind of strange. I probably should `using RCall` on the startup of `julia_console()` and do the setup.

**Comment by randy3k** [comment]
It is expected that `using RCall` does not trigger `RCall.__init__()`. It is common to have multiple `using RCall` statements in a Julia session, `__init__()` will only be triggered when a package is loaded first time.

**Comment by randy3k** [comment]
You may also need to run `rgui_start` and `rgui_stop()` before and after `julia_console()`.

**Comment by randy3k** [comment]
You could just execute `RCall.__init__()` in the `setup.jl`.

**Comment by Non-Contradiction** [comment]
When `JuliaCall` sources `setup.jl` in embedded julia, julia is not in the interactive use. So even `RCall.__init__()` explicitly, things like REPL won't set up. Do I understand correctly?

**Comment by randy3k** [comment]
Ai, you are correct. In fact, we shouldn't call `__init__()` explicitly. It may break other things.

Perhaps, you should just execute `repl_init()` when `! repl_inited()`.
