### ISSUE TITLE
Add c:/users/user/Documents/R/win-library/3.x to .libPaths

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaInterop/RCall.jl#206]
I am running Windows 10 64bit Pro and my libraries install to "c:/Users/username/Documents/R/win-library/3.x" instead of "C:/Users/username/R/win-library/3.4" 

which was the default for me hence it would be worthwhile adding support for that

**Comment by simonbyrne** [comment]
I'm not sure I understand, I don't think we change `.libPaths`. Does `.libPaths()` give you different values if run through R and RCall.jl?

**Comment by xiaodaigh** [comment]
@simonbyrne I am perplexded a bit. Actually I tested it both RCall and R gives me the same .libPaths() but Rstudio gives me a different one.

So I think it's an issue with RStudio.

**Comment by xiaodaigh** [comment]
Yeah. RCall.jl gives a different .libPaths()

I tried checking the R.home() and they both gave me the "same" location. Actually RCall gave me
"C:/Program Files/R/R-3.4.2"

But R and Rstudio gave me "C:/PROGRA~1/R/R-34~1.2"

**Comment by simonbyrne** [comment]
Ah that helps. It looks like we're not setting HOME correctly.

**Comment by simonbyrne** [comment]
Should now be fixed by #207
