### ISSUE TITLE
Cannot Install RCall in Julia 0.6.0 on Scientific Linux 7

### ISSUE THREAD

**Issue by virenp** [JuliaInterop/RCall.jl#218]
Hello. I have an issuing with installing RCall. My system is Scientific Linux 7 64-bit. I am using the Modules software management package and have installed R 3.4.3 and Julia 0.6.0. I also created ~/.juliarc.jl file with the following entry:

ENV["R_HOME"] = "/sw/Pkgs/R/3.4.3/lib64/R"

I start by loading the modules
$ module load R
$ module load julia
$ module list
Currently Loaded Modulefiles:
  1) java/1.8.0_152   2) R/3.4.3          3) julia/0.6.0

Check availability of R

$ which R
/sw/Pkgs/R/3.4.3/bin/R

Then I start Julia:

$ export LD_LIBRARY_PATH=`R RHOME`/lib
$ julia --startupfile=yes

              _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.0 (2017-06-19 13:05 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> ENV["R_HOME"]
"/sw/Pkgs/R/3.4.3/lib64/R"

julia> ENV["LD_LIBRARY_PATH"]
"/sw/Pkgs/R/3.4.3/lib64/R/lib"

julia> Pkg.add("RCall")
INFO: Initializing package repository /home/vpatel/.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of AxisArrays from https://github.com/JuliaArrays/AxisArrays.jl.git
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of CategoricalArrays from https://github.com/JuliaData/CategoricalArrays.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of DataArrays from https://github.com/JuliaStats/DataArrays.jl.git
INFO: Cloning cache of DataFrames from https://github.com/JuliaData/DataFrames.jl.git
INFO: Cloning cache of DataStreams from https://github.com/JuliaData/DataStreams.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
INFO: Cloning cache of GZip from https://github.com/JuliaIO/GZip.jl.git
INFO: Cloning cache of IntervalSets from https://github.com/JuliaMath/IntervalSets.jl.git
INFO: Cloning cache of IterTools from https://github.com/JuliaCollections/IterTools.jl.git
INFO: Cloning cache of Missings from https://github.com/JuliaData/Missings.jl.git
INFO: Cloning cache of NamedTuples from https://github.com/blackrock/NamedTuples.jl.git
INFO: Cloning cache of RCall from https://github.com/JuliaInterop/RCall.jl.git
INFO: Cloning cache of RangeArrays from https://github.com/JuliaArrays/RangeArrays.jl.git
INFO: Cloning cache of Reexport from https://github.com/simonster/Reexport.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of SortingAlgorithms from https://github.com/JuliaCollections/SortingAlgorithms.jl.git
INFO: Cloning cache of SpecialFunctions from https://github.com/JuliaMath/SpecialFunctions.jl.git
INFO: Cloning cache of StatsBase from https://github.com/JuliaStats/StatsBase.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of WeakRefStrings from https://github.com/quinnj/WeakRefStrings.jl.git
INFO: Installing AxisArrays v0.2.0
INFO: Installing BinDeps v0.8.0
INFO: Installing CategoricalArrays v0.3.0
INFO: Installing Compat v0.38.0
INFO: Installing DataArrays v0.7.0
INFO: Installing DataFrames v0.11.1
INFO: Installing DataStreams v0.3.1
INFO: Installing DataStructures v0.7.2
INFO: Installing GZip v0.3.0
INFO: Installing IntervalSets v0.1.1
INFO: Installing IterTools v0.1.0
INFO: Installing Missings v0.2.2
INFO: Installing NamedTuples v4.0.0
INFO: Installing RCall v0.9.0
INFO: Installing RangeArrays v0.2.0
INFO: Installing Reexport v0.0.3
INFO: Installing SHA v0.5.2
INFO: Installing SortingAlgorithms v0.2.0
INFO: Installing SpecialFunctions v0.3.5
INFO: Installing StatsBase v0.19.2
INFO: Installing URIParser v0.2.0
INFO: Installing WeakRefStrings v0.4.0
INFO: Building SpecialFunctions
INFO: Package database updated

ulia> using RCall
INFO: Precompiling module RCall.
ERROR: LoadError: LoadError: Could not find R installation. Either set the "R_HOME" environmental variable, or ensure the R executable is available in "PATH".
Stacktrace:
 [1] locate_Rhome_libR() at /home/vpatel/.julia/v0.6/RCall/src/setup.jl:118
 [2] include_from_node1(::String) at ./loading.jl:569
 [3] include(::String) at ./sysimg.jl:14
 [4] include_from_node1(::String) at ./loading.jl:569
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /home/vpatel/.julia/v0.6/RCall/src/setup.jl, in expression starting on line 121
while loading /home/vpatel/.julia/v0.6/RCall/src/RCall.jl, in expression starting on line 37
ERROR: Failed to precompile RCall to /home/vpatel/.julia/lib/v0.6/RCall.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398

**Comment by randy3k** [comment]
Was the R built with shared library `libR.so`? Have a quick check of the directory `/sw/Pkgs/R/3.4.3/lib64/R/lib`.

If it was not the case, you should ask your system administrator to rebuild R with `--enable-R-shlib`.

**Comment by virenp** [comment]
Yes, that was the issue (also identified in another post which I should have checked). Thanks.
