### ISSUE TITLE
Array representation changes when Array contains Missings.Missing values

### ISSUE THREAD

**Issue by ValdarT** [JuliaInterop/RCall.jl#219]
```
using RCall, Missings
v1 = [1,2,3,4]
R"$v1" # gives r vector (RCall.RObject{RCall.IntSxp})
v2 = [1,2,missing,4]
R"$v2" # gives r list (RCall.RObject{RCall.VecSxp})
```

I'm using Julia 0.6.1, Missings v0.2.4, RCall v0.9.0.

**Comment by randy3k** [comment]
This is expected as `v2` is `Array{Any}`. Use DataArrays for constructing a vector containing missings.

**Comment by ValdarT** [comment]
`v2` is not `Array{Any}`, it is ` Array{Union{Int64, Missings.Missing}}`. Since this is the new default way of handling missing data, I think it is very important to handle it correctly in R interop.

**Comment by randy3k** [comment]
You are right. In the meanwhile, use DataArrays as a workaround. I will look at it when I have time. If you are interested in making a pull request, the corresponding codes are under `src/convert/base.jl` and  `src/convert/default.jl`

**Comment by randy3k** [comment]
I have just added support of `Array{Union{T, Missing}}`. The Julia -> R direction should be seamless. The R -> Julia direction requires an explicit type specification `rcopy(Array{Union{Int, Missing}}, R"c(1, 2, NA)")`

**Comment by randy3k** [comment]
Since  bb63be9, the default conversion for vectors containing NAs would be `Array{Union{T, Missing}}`
