### ISSUE TITLE
Method error with RCall 0.9 and DataFrames 0.11.3

### ISSUE THREAD

**Issue by protogeezer** [JuliaInterop/RCall.jl#220]
Trying to convert a data frame containing a PooledDataArray to R results in a MethodError
julia> r = RObject(j1)
ERROR: MethodError: no method matching sexp(::Type{RCall.StrSxp}, ::DataArrays.PooledDataArray{String,UInt16,1})
Closest candidates are:
  sexp(::Type{RCall.StrSxp}, ::Symbol) at /Users/sjbespa/.julia/v0.6/RCall/src/convert/base.jl:217
  sexp(::Type{RCall.StrSxp}, ::Ptr{RCall.CharSxp}) at /Users/sjbespa/.julia/v0.6/RCall/src/convert/base.jl:266
  sexp(::Type{RCall.StrSxp}, ::AbstractString) at /Users/sjbespa/.julia/v0.6/RCall/src/convert/base.jl:267
  ...
Stacktrace:
 [1] sexp(::DataArrays.PooledDataArray{String,UInt16,1}) at /Users/sjbespa/.julia/v0.6/RCall/src/convert/default.jl:192
 [2] sexp(::Type{RCall.VecSxp}, ::DataFrames.DataFrame) at /Users/sjbespa/.julia/v0.6/RCall/src/convert/dataframe.jl:19
 [3] RCall.RObject(::DataFrames.DataFrame) at /Users/sjbespa/.julia/v0.6/RCall/src/convert/default.jl:166

**Comment by randy3k** [comment]
Try updating DataArrays. The new version of DataArrays has deprecated PooledDataArray.

**Comment by protogeezer** [comment]
I tried updating to the master on RCall and DataArrays, but the same thing is happening

julia> Pkg.status("RCall")
 - RCall                         0.9.0+             master

julia> Pkg.status("DataArrays")
 - DataArrays                    0.7.0              master

julia> Pkg.status("DataFrames")
 - DataFrames                    0.11.3

**Comment by randy3k** [comment]
You should use [CategoricalArrays.jl](https://github.com/JuliaData/CategoricalArrays.jl/tree/master/src) instead of PooledDataArrays.

**Comment by palday** [comment]
Closing as very stale at this point
