### ISSUE TITLE
Failed to precompile RCall

### ISSUE THREAD

**Issue by robinkim28** [JuliaInterop/RCall.jl#221]
Hi, 

I am running Jupyter Lab from a remote server, and after installing Rcall using Pkg.add() method, I have problems when trying to import the package. I have removed the package and reinstalled it and the problem still persists.

[In] Base.compilecache("RCall")

[Out] Failed to precompile RCall to /home/hcmg/robinkim/.julia/lib/v0.6/RCall.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703

[In] using RCall
[Out] Failed to precompile RCall to /home/hcmg/robinkim/.julia/lib/v0.6/RCall.ji.

Stacktrace:
 [1] compilecache(::String) at ./loading.jl:703
 [2] _require(::Symbol) at ./loading.jl:490
 [3] require(::Symbol) at ./loading.jl:398

**Comment by randy3k** [comment]
It isn’t clear to me what the reason of failing is. Could you trying running it on a julia console on the remote server?

**Comment by robinkim28** [comment]
It turns out the R version on the remote server was outdated.

ERROR: LoadError: LoadError: R library /usr/lib64/R/lib/libR.so appears to be too old. RCall.jl requires R 3.4.0 or later

Will close this after confirming that updating R fixes the problem.
