### ISSUE TITLE
Unable to use R and RCall installed via conda.jl 

### ISSUE THREAD

**Issue by abhi18av** [JuliaInterop/RCall.jl#224]
Hi **JuliaInterop** team :)

I've been gearing up to introduce Julia to my organization where R , Python and Conda are heavily used. So, I was evaluating this package as a possible solution to tie the goals together.

I've setup conda, conda-forge and python properly 

```julia

using Conda

Conda.list()

Conda.add_channel("conda-forge")

```

Here's the issue I'm running into 

```julia 
Conda.add("r-base")

# TODO Fix the path issues
ENV["LD_LIBRARY_PATH"] = "/Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/lib/R/lib/libR.dylib"
Pkg.build("RCall")

using RCall
R"rnorm(10)"

```

However calling Python2 from Julia works fine 

```julia 
ENV["PYTHON"] = "/Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/bin/python2.7"
Pkg.build("PyCall")


using PyCall


@pyimport sys
sys.version

```

Could you please help me out to set the path properly for R ?

**Comment by abhi18av** [comment]
The error message is as follows 

```
validate_libR(::String) at /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/RCall/src/setup.jl:15
 [2] locate_Rhome_libR() at /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/RCall/src/setup.jl:114
 [3] include_from_node1(::String) at ./loading.jl:576
 [4] include(::String) at ./sysimg.jl:14
 [5] include_from_node1(::String) at ./loading.jl:576
 [6] include(::String) at ./sysimg.jl:14
 [7] anonymous at ./<missing>:2
while loading /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/RCall/src/setup.jl, in expression starting on line 121
while loading /Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/RCall/src/RCall.jl, in expression starting on line 41
```

**Comment by randy3k** [comment]
It could be done by setting the `R_HOME` variable and exporting `LD_LIBRARY_PATH`. You, however, need to make sure the `LD_LIBRARY_PATH` is set before launching julia. Also, it should be just `"/Applications/JuliaPro-0.6.2.1.app/Contents/Resources/pkgs-0.6.2.1/v0.6/Conda/deps/usr/lib/R/lib"`.

**Comment by abhi18av** [comment]
Thanks 👍 

This worked perfectly!😄

**Comment by simonbyrne** [comment]
We should check for this in setup.jl.

**Comment by randy3k** [comment]
AFAIK, there is no way to set `LD_LIBRARY_PATH` after julia is launched.

**Comment by simonbyrne** [comment]
Ah right. We could perhaps detect it and throw an informative error though.

**Comment by stevengj** [comment]
Why can't `Pkg.build("RCall")` just find the full path of `libR` and use that?   You shouldn't depend on environment variables for library paths.

In particular, I would recommend using Conda by default on Mac and Windows, and on Linux/BSD use it as a fallback when `libR` is not found.

**Comment by stevengj** [comment]
Right now, you locate libR when you precompile.  It would be more normal to do this during `Pkg.build`.   This has the advantage that you can re-run `Pkg.build` to reconfigure the R location.    Conversely, it means that you can cache the R location during the build, so that it remembers it the next time you do `Pkg.update`, which is especially important if the user set up their environment specially during build to ensure that R was found.

**Comment by stevengj** [comment]
Note that once #229 is merged, it will *automatically* use Conda to install R if no working R version is found, and you can force it to use Conda by setting `ENV["R_HOME"]="*"` (*once*, during `Pkg.build`).
