### ISSUE TITLE
InitError when using RCall

### ISSUE THREAD

**Issue by cossio** [JuliaInterop/RCall.jl#225]
I just installed RCall, but I cannot use it. Here is the error I get:

![image](https://user-images.githubusercontent.com/10637482/36379942-7e367556-154e-11e8-9d1b-13326006a5b6.png)

I am using Julia v0.6.2, RCall v0.8.1. I have not imported any other packages.

**Comment by nalimilan** [comment]
What version are you using? Have you loaded other packages too? The Nulls package isn't supposed to be loaded, and it conflicts with Missings.

**Comment by cossio** [comment]
@nalimilan  I ahve Nulls and Missings installed. But I had not imported any them (or any other packages).

**Comment by nalimilan** [comment]
So what's your RCall version?

**Comment by cossio** [comment]
v0.8.1

**Comment by nalimilan** [comment]
You should update to the latest version then (0.10.1).

**Comment by cossio** [comment]
@nalimilan  How can I do that? I just installed RCall today. Shouldn't it have added the latest version by default?

**Comment by nalimilan** [comment]
You probably have packages installed that require DataFrames 0.10.1. See https://discourse.julialang.org/t/how-to-upgrade-from-dataframes-0-10-1-to-0-11-3/8243/.

**Comment by cossio** [comment]
@nalimilan Yes, that fixed the problem. Thanks.
