### ISSUE TITLE
Problem saving plots from `plot.___`

### ISSUE THREAD

**Issue by diegozea** [JuliaInterop/RCall.jl#231]
Saving figures from R `plot(...` works fine. However, I get empty files when I try to use `plot.euler` from the `eulerr` package.

```julia
using RCall

R"""
library(eulerr)
fit <- euler(c("A" = 25, "B" = 5, "C" = 5,
               "A&B" = 5, "A&C" = 5, "B&C" = 3,
               "A&B&C" = 3))
svg("example.svg")

plot(fit)

dev.off()
"""
```

However, I tried this and It worked fine:

```julia
using RCall

R"""
library(eulerr)
fit <- euler(c("A" = 25, "B" = 5, "C" = 5,
               "A&B" = 5, "A&C" = 5, "B&C" = 3,
               "A&B&C" = 3))

svg("example.svg")
"""

rprint(R"plot(fit)")

R"dev.off()"
```

**Comment by diegozea** [comment]
Trying that inside of a function in IJulia is a little more tricky. `dev.off()` gives an error that I solved using:
```julia
R"""
if(names(dev.cur()) == c("svg")){dev.off()}
"""
```

**Comment by randy3k** [comment]
Due to the implementation of `plot.euler`. You will need to `print` the plot. 

```
using RCall

R"""
library(eulerr)
fit <- euler(c("A" = 25, "B" = 5, "C" = 5,
               "A&B" = 5, "A&C" = 5, "B&C" = 3,
               "A&B&C" = 3))
svg("example.svg")
print(plot(fit))
dev.off()
"""
```

Did you put `dev.off()` in a different cell in IJulia? In IJulia/juptyer, Each cell is designated with a device to capture plots so the `svg` device should be opened and closed in the same cell.

**Comment by diegozea** [comment]
The plot command and the dev.off are used in a function definition, then the function is called in the other cells. That function with the R macro in its body works fine in a script but It throws the error in IJulia.

**Comment by randy3k** [comment]
is it possible for you to share your notebook or make a minimal example out of it?

**Comment by palday** [comment]
closing as stale
