### ISSUE TITLE
@rlibrary and arguments with dots

### ISSUE THREAD

**Issue by aterenin** [JuliaInterop/RCall.jl#234]
I can't find any documentation on how functions and keyword arguments like `data.frame` or `na.rm` that contain dots get translated into Julia. Are these imported at all?

**Comment by aterenin** [comment]
Figured it out - the correct syntax is `geom_point(; Symbol("na.rm")=>true)`.

It would be great to document this.

**Comment by randy3k** [comment]
This is one of the reasons why `@rlibrary` has not yet been documented.

**Comment by aterenin** [comment]
What do you mean? It's not documented because dots are not removed and therefore the syntax may look a bit strange?

**Comment by randy3k** [comment]
more or less. There are also other issues to be considered. For example, under current implementation, functions which have names containing dots also cannot be called directory when using `@rlibrary`. It would be kept internal until we find good solutions to those issues.

**Comment by aterenin** [comment]
Has there been any discussion on how to handle this? It seems the main issue here is not Julia capabilities - the functions can be called right now through code such as `getfield(base,Symbol("data.frame"))` - but rather what API to select to handle the issue.

One proposal could be to add syntax allowing the user to decide what substitution to make. For example
```julia
@rlibrary ggplot2 "."=>"_"
```
might import ggplot2, substituting all dots in function names and arguments with underscores.

**Comment by nalimilan** [comment]
Why not always replace dots with underscores? Working with dots in objects names is so painful in Julia that I don't think anybody would want to do that.

**Comment by randy3k** [comment]
Handling the object names with dots is not only secondary, a more important issue is that R is lazy and it makes some function calls not working properly, see #42 for some discussions.

**Comment by aterenin** [comment]
I've now also learned that we can do `geom_point(var"na.rm" = true)` and `@rimport base; var"data.frame"()` or even `R"data.frame"()` which are sufficiently clean that I'm not bothered by a lack of syntax for dots anymore.

I think this should be documented. I think this is a separate issue from functions being broken by lazy evaluation, because not all packages use lazy evaluation and case-by-case workarounds are possible for those willing to take a bit of time to figure out what to do.

**Comment by randy3k** [comment]
I have added a small section to document `@rlibrary` b388815
