### ISSUE TITLE
Mention the R package JuliaCall

### ISSUE THREAD

**Issue by dmbates** [JuliaInterop/RCall.jl#235]
I saw mention of the R package [`JuliaCall`](https://non-contradiction.github.io/JuliaCall//index.html) and was going to suggest that the author mention the `RCall` package in the documentation.  Then it occurred to me that it would be reasonable to offer reciprocal mentions.

I think there is more than one R package to call Julia and I haven't looked in detail at them.  Any opinions?

**Comment by Non-Contradiction** [comment]
I just mentioned the RCall and simply wrote about other R packages (XRJulia and RJulia) to call Julia in a section in README <https://github.com/Non-Contradiction/JuliaCall#interfaces-between-r-and-julia>.
