### ISSUE TITLE
Conversion of R formula objects

### ISSUE THREAD

**Issue by dmbates** [JuliaInterop/RCall.jl#236]
I plan to look into converting an R formula object to `StatsModels.Formula` in Julia.  There was a function to convert a Julia formula to an R formula but it is now commented out (at the end of `base.jl`).  Going the other way one needs to take an `RCall.LangSxp` with class `"formula"` and pull apart its pieces.

```julia
julia> f = reval("y ~ 1 + a + b")                   
RCall.RObject{RCall.LangSxp}                        
y ~ 1 + a + b             

julia> getclass(f)          # class will be the string "formula"
RCall.RObject{RCall.StrSxp}                         
[1] "formula"`

julia> length(f)             # it's a two-argument call
3

julia> f[1]                    # symbol being called is '~'
RCall.RObject{RCall.SymSxp}
`~`

julia> f[2]                   # lhs is the symbol y
RCall.RObject{RCall.SymSxp}
y

julia> f[3]                  # rhs is another call - actually parses to :((1 + a) + b) in Julia
RCall.RObject{RCall.LangSxp}
1 + a + b

julia> f[3][1]
RCall.RObject{RCall.SymSxp}
`+`

julia> f[3][2]
RCall.RObject{RCall.LangSxp}
1 + a

julia> f[3][3]
RCall.RObject{RCall.SymSxp}
b

julia> f[3][2][1]
RCall.RObject{RCall.SymSxp}
`+`

...
```

It has been some time since I looked at the internals of `RCall`.  If someone could give me some direction on what would be needed to take an R formula and generate the equivalent expressions in Julia I would appreciate it.

By the way, the Julia `Formula` struct is now defined in the `StatsModels` package.

**Comment by kleinschmidt** [comment]
Seems pretty straightforward to just convert from the `SymExp` to `Symbol` and `LangExp` to native Julia `Expr` and pass that to the `Formula(lhs, rhs)` constructor.  Is there some additional complexity that I'm missing?  I guess the interaction syntax is different but that's about all I can think of...

**Comment by dmbates** [comment]
@kleinschmidt I agree.  I was just wondering what the sequence of operations is to make it mesh with something like `rcopy`.  Right now `rcopy` doesn't do anything to an `RCall.LangSxp` because there isn't always a 1-1 map from an R function call to a Julia function call.  Contrast
```julia
julia> R"datasets::Formaldehyde"
RCall.RObject{RCall.VecSxp}
  carb optden
1  0.1  0.086
2  0.3  0.269
3  0.5  0.446
4  0.6  0.538
5  0.7  0.626
6  0.9  0.782


julia> rcopy(R"datasets::Formaldehyde")
6×2 DataFrames.DataFrame
│ Row │ carb │ optden │
├─────┼──────┼────────┤
│ 1   │ 0.1  │ 0.086  │
│ 2   │ 0.3  │ 0.269  │
│ 3   │ 0.5  │ 0.446  │
│ 4   │ 0.6  │ 0.538  │
│ 5   │ 0.7  │ 0.626  │
│ 6   │ 0.9  │ 0.782  │
```
with
```julia
julia> R"y ~ 1 + a + b"
RCall.RObject{RCall.LangSxp}
y ~ 1 + a + b


julia> rcopy(R"y ~ 1 + a + b")
RCall.RObject{RCall.LangSxp}
y ~ 1 + a + b
```

**Comment by randy3k** [comment]
With current master 7f483ce9be2f3e2d1c276d21faf3888571f056a7, a custom converter could be defined as follow

```julia
import RCall: rcopy, SymSxp, LangSxp, RClass, rcopytype
import StatsModels:Formula

rcopytype(::Type{RClass{:call}}, l::Ptr{LangSxp}) = Expr

function RCall.rcopy(::Type{Expr}, l::Ptr{LangSxp})
    Expr(:call, [rcopy(s) for s in l]...)
end

rcopytype(::Type{RClass{:formula}}, l::Ptr{LangSxp}) = Formula

function RCall.rcopy(::Type{Formula}, l::Ptr{LangSxp})
    Formula(rcopy(l[2]), rcopy(l[3]))
end

rcopy(R"a ~ b + 1")

```

**Comment by randy3k** [comment]
I have just tagged v0.10.2. Hope it will appear in METADATA soon.

**Comment by randy3k** [comment]
@dmbates v0.10.2 is out. You should be able to make the conversion as above. However, I am now working on a refactoring of the LangSxp's `getindex` and `setindex!` which may affect the above code in the further releases.

**Comment by randy3k** [comment]
@dmbates Am I right that StatsModels and GLM do not support polynomial terms? I want to convert `y ~ x + I(x^2)` and cannot find any equivalence.

**Comment by dmbates** [comment]
@randy3k Yes, StatsModels does not support polynomial terms.  It also, if i remember correctly, doesn't have an `I(...)` wrapper.

**Comment by kleinschmidt** [comment]
Correct on both counts

**Comment by dmbates** [comment]
@randy3k Would you be okay with adding a dependence of `RCall` on `StatsModels` and putting the conversion of R formulas to Julia formulas in `RCall`?

**Comment by kleinschmidt** [comment]
Right now that dependence might be undesirable: statsmodels still depends on dataframes

**Comment by dmbates** [comment]
`RCall` already depends on `DataFrames`.

**Comment by kleinschmidt** [comment]
...I juuust thought to check that :)

**Comment by kleinschmidt** [comment]
@dmbates I think the floating points should be converted to Ints but checking that they're a valid value...anything else isn't going to be supported in our Formulas anyway (at the moment)

**Comment by dmbates** [comment]
There are several other conversions that would need to be wired in for the special case of R formulas.  We know about `: => &`.  Also R formulas retain parenthesized terms as having a special type.
```julia
julia> f = R"y ~ 1 + a + (1|g)"
RCall.RObject{RCall.LangSxp}
y ~ 1 + a + (1 | g)


julia> f[3]
RCall.RObject{RCall.LangSxp}
1 + a + (1 | g)


julia> f[3][3]
RCall.RObject{RCall.LangSxp}
(1 | g)


julia> getclass(f[3][3])
RCall.RObject{RCall.StrSxp}
[1] "("
```

**Comment by randy3k** [comment]
@dmbates actually I am working on it, that’s way I asked.

**Comment by dmbates** [comment]
@randy3k Okay, great.  Thanks.  I'll leave you to it.

**Comment by randy3k** [comment]
I have pushed some code to master. The conversion should be working in most cases. Special care has been taken to handle integers when converting formulas from R to julia. Specifically, `1` in R is double and it is converted to `1` but not `1.0`. But I am not sure about the other direction, is `(1L | g)` an functionable result at all?

```julia
julia> rcopy(R"y ~ x + (1 | g)")
Formula: y ~ x + (1 | g)

julia> RObject(@formula y ~ x + (1 | g))
RCall.RObject{RCall.LangSxp}
y ~ x + (1L | g)
```

**Comment by dmbates** [comment]
That looks great, @randy3k .  I'm impressed with the thorough job that you did.  Thank you.

Do you plan to make a new release soon?

**Comment by randy3k** [comment]
I'll make a release once https://github.com/Non-Contradiction/JuliaCall/issues/34 is fixed.

**Comment by dmbates** [comment]
Sounds good.  Thanks.

**Comment by dmbates** [comment]
Is https://github.com/Non-Contradiction/JuliaCall/issues/34 considered fixed yet?
