### ISSUE TITLE
cryptic warning: "incremental compilation may be broken for this module"

### ISSUE THREAD

**Issue by cecileane** [JuliaInterop/RCall.jl#238]
My apologies in advance for not providing a good diagnostic. I get many warnings during the precompilation of [PhyloPlots](https://github.com/cecileane/PhyloPlots.jl), which uses RCall:

```
julia> using PhyloPlots
INFO: Recompiling stale cache file /Users/ane/.julia/lib/v0.6/PhyloPlots.ji for module PhyloPlots.
WARNING: eval from module Const to PhyloPlots:    
Expr(:block, Expr(:line, 73, Symbol("/Users/ane/.julia/v0.6/RCall/src/Const.jl"))::Any, Expr(:., :NaString, Expr(:quote, :p)::Any)::Any = Expr(:call, :unsafe_load, Expr(:call, :cglobal, "R_NaString", Expr(:call, :typeof, Expr(:., :NaString, Expr(:quote, :p)::Any)::Any)::Any)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **

[...]

WARNING: eval from module Const to PhyloPlots:    
Expr(:block, Expr(:line, 73, Symbol("/Users/ane/.julia/v0.6/RCall/src/Const.jl"))::Any, Expr(:., :UnboundValue, Expr(:quote, :p)::Any)::Any = Expr(:call, :unsafe_load, Expr(:call, :cglobal, "R_UnboundValue", Expr(:call, :typeof, Expr(:., :UnboundValue, Expr(:quote, :p)::Any)::Any)::Any)::Any)::Any)::Any
  ** incremental compilation may be broken for this module **
```
There is one such warning for each symbol in the loop in the definition of `load` in [Const.jl](https://github.com/JuliaInterop/RCall.jl/blob/master/src/Const.jl#L57). I checked out the master branch of PhyloPlots and PhyloNetworks, and RCall v0.10.3. Just warnings though, no error so far.

**Comment by randy3k** [comment]
How about RCall v0.10.2?

**Comment by cecileane** [comment]
Things look good with RCall v0.10.2, indeed: I do *not* get these warnings and all the PhyloPlots tests pass.

**Comment by randy3k** [comment]
It seems like we cannot use `@eval` in `__init__()`.

**Comment by randy3k** [comment]
Should be fixed by 9e3b0f1cfec357936fb5eff61c06de2e6b3aa89a.

Thanks for the report. I will make a release soon.

**Comment by randy3k** [comment]
Just tag a new release https://github.com/JuliaLang/METADATA.jl/pull/14074.

**Comment by cecileane** [comment]
yes, this is fixed 👍 . thank you!
