### ISSUE TITLE
Problematic R"1:2" with R 3.5?

### ISSUE THREAD

**Issue by Non-Contradiction** [JuliaInterop/RCall.jl#241]
It seems that R 3.5 is going to release soon. I download R 3.5 and find that:
```
using RCall

rcopy(R"1")

# 1.00

rcopy(R"1:2")

# Int64[2]
# 679219440
# 32648

rcopy(R"c(1:2)")

# Int64[2]
# 1
# 2
```
 
I kind of read something like R 3.5 will delay evaluation on things like `1:2`, this problem may be related to this.

**Comment by randy3k** [comment]
I believe that it is related to https://svn.r-project.org/R/branches/ALTREP/ALTREP.html

**Comment by randy3k** [comment]
https://cran.r-project.org/doc/manuals/r-devel/NEWS.html
> Arithmetic sequences created by 1:n, seq_along, and the like now use compact internal representations via the ALTREP framework.

**Comment by Non-Contradiction** [comment]
From the documentation, the `duplicate` method can obtain a non-ALTREP representation.
```
@eval RCall duplicate(s::Ptr{S}) where S<:Sxp = ccall(("Rf_duplicate",libR),Ptr{S},(Ptr{SxpPtrInfo},),s)
@eval RCall duplicate(s::RObject) = RObject(duplicate(s.p))

rcopy(RCall.duplicate(R"1:3"))

# Int64[3]
# 1
# 2
# 3

rcopy(R"1:3")

# Int64[3]
# -1979458880
# 32693
# 2
```

Is it a good idea to incorporate a function like `duplicate` into `rcopy` to temporarily solve the issue?

**Comment by randy3k** [comment]
I may be a better idea to fix the root of the issue. The cause of the issue is we were too smart to use the pointer [directly](https://github.com/JuliaInterop/RCall.jl/blob/81589047a24ba3406b7e9817b688d74ab086aa43/src/methods.jl#L41). A quick solution (untested) is
```
dataptr(s::Ptr{S}) where S<:VectorSxp = ccall(("DATAPTR",libR),Ptr{eltype(S)},(Ptr{SxpPtrInfo},),s)
```

**Comment by randy3k** [comment]
I just checked that `DATAPTR` is only available on R 3.5. It means we need to check the R version and dispatch the correct method.

**Comment by randy3k** [comment]
I don't have R 3.5 installed, @Non-Contradiction  would you check if the above change fixes the issue?

**Comment by Non-Contradiction** [comment]
The change causes segfault on my machine.

**Comment by randy3k** [comment]
Um, interesting. Let it install R 3.5 and test it.

**Comment by randy3k** [comment]
Odd, this works. I ought to convert the result to the corresponding pointer type explictly.
```
dataptr(s::Ptr{S}) where S<:VectorSxp = convert(Ptr{eltype(S)}, ccall(("DATAPTR",libR), Ptr{Void}, (Ptr{SxpPtrInfo},), s))
```

**Comment by Non-Contradiction** [comment]
The change works for me. From its signature, the result returned by `DATAPTR` is indeed a void pointer, so I guess that is the reason why it has to be converted explicitly.

**Comment by randy3k** [comment]
4906401 should be a backward compatible fix for ALTREP.

**Comment by randy3k** [comment]
I think we should make a release soon as R 3.5 will be released two days later.
