### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by donaldRwilliams** [JuliaInterop/RCall.jl#245]
Hi:
I am encountering an error when attempting to use RCall. Thus far, I have only installed and attempted to run 
````   
     using RCall
    @rlibrary ggplot2
````
where I encounter this error 

**error compiling #rcall_p#74: error compiling reval_p: error compiling #70: could not load library "C:/PROGRA~1/R/R-34~1.2/bin/x64/R"
The specified module could not be found.

rcall_p(::Symbol, ::String, ::Vararg{String,N} where N) at language.jl:49
#rcall#75(::Array{Any,1}, ::Function, ::Symbol, ::String, ::Vararg{String,N} where N) at language.jl:56
rimport(::String, ::Symbol) at namespaces.jl:22
rimport(::Symbol) at namespaces.jl:36
include_string(::String, ::String) at loading.jl:522
include_string(::String, ::String, ::Int64) at eval.jl:30
include_string(::Module, ::String, ::String, ::Int64, ::Vararg{Int64,N} where N) at eval.jl:34
(::Atom.##102#107{String,Int64,String})() at eval.jl:82
withpath(::Atom.##102#107{String,Int64,String}, ::String) at utils.jl:30
withpath(::Function, ::String) at eval.jl:38
hideprompt(::Atom.##101#106{String,Int64,String}) at repl.jl:67
macro expansion at eval.jl:80 [inlined]
(::Atom.##100#105{Dict{String,Any}})() at task.jl:80
**

**Comment by randy3k** [comment]
How about running it via julia.exe?

**Comment by donaldRwilliams** [comment]
@randy3k  What the best way to do this ?

**Comment by randy3k** [comment]
By default, julia is installed to your AppData folder.
