### ISSUE TITLE
Forcing Conda installation using ENV["R_HOME"] = "*"

### ISSUE THREAD

**Issue by cth** [JuliaInterop/RCall.jl#246]
The documentation states:

*When `R HOME` doesn't return a valid R library **or** `R_HOME` is set to `"*"`, RCall will use its own Conda installation of R.*

Hence it should be possible to force Conda based R-installation, but if a version of R (that supports `R RHOME`) is found in the path and locate_libR returns a valid path, then it is never checked whether `ENV["R_HOME"] == "*"`. Thus, in this case it is not possible to force the Conda installation. 

The easiest fix would be to change the documentation changing the **or** in quoted sentence to **and**, but I think being able to force Conda should be possible, since for some reason the default installation of R may be broken and possibly not possible to tinker with by a user.

**Comment by randy3k** [comment]
`locate_libR("*", false)` should return false. In fact, `R_HOME` is read from `R Rhome` only if `R_HOME` is empty.

You may want to make sure you have configure R_HOMEproperly.

**Comment by cth** [comment]
You're right of course. Sorry for false alarm. I had an old ENV setting in my .juliarc that was overriding my command line setting. I am closing this.
