### ISSUE TITLE
Curious about 0.7 plans

### ISSUE THREAD

**Issue by phaverty** [JuliaInterop/RCall.jl#247]
DataArrays does not load in julia 0.7. Will RCall switch to Array{Union{T,Missing}} and drop DataArrays for julia 0.7? I'm interested in helping out either DataArrays or RCall with the 0.7 transition.  If RCall will be dropping DataArrays, I'll leave that alone.

**Comment by randy3k** [comment]
RCall already supports `Array{Union(T, Missing}`. It is just a matter to deprecate or not DataArrays. Will DataArrays support Julia v0.7 eventually?

**Comment by simonbyrne** [comment]
See https://github.com/JuliaStats/DataArrays.jl/issues/301

**Comment by randy3k** [comment]
So, I guess we could remove the support of DataArray for the julia v0.7 only release.

**Comment by randy3k** [comment]
I finally could find some time to fix the v0.7 compatibility issue.
