### ISSUE TITLE
Building RCall on Ubuntu 16.04.4 with R built on sources

### ISSUE THREAD

**Issue by theogf** [JuliaInterop/RCall.jl#253]
Hello,

I have exactly the same problem that #243  got, except that adding the library path via export is not helping at all. I correctly set `ENV["R_HOME"]` as well as `ENV["PATH"]` but I always end up with the error :
```julia
INFO: Building RCall
================================[ ERROR: RCall ]================================

LoadError: unlink: no such file or directory (ENOENT)
while loading /data/home/fajou/.julia/v0.6/RCall/deps/build.jl, in expression starting on line 57
```
This is using R 3.5.1 amd

```julia
julia> versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb (2018-07-09 19:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)

```

**Comment by randy3k** [comment]
How about setting `LD_LIBRARY_PATH`?

**Comment by theogf** [comment]
I indeed tried  `export LD_LIBRARY_PATH` with the R.home() environment but it does not help

**Comment by randy3k** [comment]
How about
```
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
```

**Comment by theogf** [comment]
I am sorry for not being explicit enough.
I indeed use 
```sh
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"
```
But I still get the same error. One thing is that I did not install R myself. The admin of the server did it himself. He might have done something shady that is now interfering.

**Comment by randy3k** [comment]
then you might need to locate where the R shared library is located.

**Comment by theogf** [comment]
Well that's what 
```R
R.home()
```
is telling me if I am not mistaking. In my case it returns
```R
[1] "/opt/R/lib/R"
```
I tried all combinations with "/opt/R/lib", "/opt/R/lib/R/lib" and even "/opt/R/lib/R" but none works.

Just to be sure :
I am first doing `export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/opt/R/lib/R/lib"` in my terminal, and then run Julia, set `ENV["R_HOME"] = "/opt/R/lib/R"` and finish by `Pkg.build("RCall)` (I automatically add the R executable location in my PATH)

**Comment by randy3k** [comment]
Your steps are right. BTW, does `/opt/R/lib/R/lib/libR.so` exist?

**Comment by theogf** [comment]
I ended up solving my problem by writing my own `deps/deps.jl` file (I had a healthy one on my own machine) and not setting `ENV["R_HOME"]`. I also made my own local install of R via Anaconda.
Thanks for the help

**Comment by randy3k** [comment]
Do you happen to know the reason for the cause?

**Comment by theogf** [comment]
I think it might due that, as you apparently suspected, the manual installation on the server did not produce `libR.so`, while the Anaconda installation did...

**Comment by randy3k** [comment]
Ya, it might be possible that your server's R was not installed with the flag `--enable-R-shlib`.

**Comment by randy3k** [comment]
No, RCall doesn't manage the CPU resource for R. In fact, R has very little support of real parallelization. Some level of parallelization could be archived by package `parallel` via forking and by using lower level linear algebra library such as `openblas`.

**Comment by randy3k** [comment]
In your case, I bet it is a linear algebra library being used which is exhausting the CPU.

**Comment by theogf** [comment]
That's the weird thing, there was indeed a call to `library(doMC)` which uses parallelization, but even after removall, all CPUs keep being used!
