### ISSUE TITLE
Is LD_LIBRARY_PATH the only way?

### ISSUE THREAD

**Issue by lbilli** [JuliaInterop/RCall.jl#268]
I can use `RCall` only if I start `julia` like this:
```
LD_LIBRARY_PATH=/usr/lib64/R/lib julia
```
otherwise the linker can't find `libRblas.so`, as it has already been discussed.
I was wondering if that's still the only way. I've tried adding:
```
 ENV["LD_LIBRARY_PATH"] = "/usr/lib64/R/lib"
```
in `startup.jl` but that doesn't work.

**Comment by randy3k** [comment]
The environment variable has to be set before Julia is loaded.

You could patchelf libR.so (if you know what it means). Otherwise, there is no other fixes.

**Comment by lbilli** [comment]
Got it. Thanks!

**Comment by lbilli** [comment]
As of Julia 1.7.2 it looks like specifying `LD_LIBRARY_PATH` is not required anymore.
