### ISSUE TITLE
Error with conda install on Windows

### ISSUE THREAD

**Issue by JackDunnNZ** [JuliaInterop/RCall.jl#269]
If I try to force the install via conda on Windows like following:

```julia
ENV["R_HOME"] = "*"
Pkg.build("RCall")
```

I get an error, because it tries to call `isdir("*")` which seems to error on Windows

**Comment by randy3k** [comment]
Please check if 72dc8a1 fixes your issue.

**Comment by JackDunnNZ** [comment]
Thanks for the quick response! That moves the error one step forward to `isfile("*")` in `validate_libR`

```
┌ Error: Error building `RCall`:
│ ERROR: LoadError: IOError: stat: invalid argument (EINVAL)
│ Stacktrace:
│  [1] stat(::String) at .\stat.jl:68
│  [2] isfile at .\stat.jl:303 [inlined]
│  [3] validate_libR(::String, ::Bool) at C:\Users\Jack\.julia\dev\RCall\deps\setup.jl:12
│  [4] locate_libR(::String, ::Bool) at C:\Users\Jack\.julia\dev\RCall\deps\setup.jl:53
│  [5] top-level scope at logging.jl:317
│  [6] top-level scope at C:\Users\Jack\.julia\dev\RCall\deps\build.jl:19
│  [7] include at .\boot.jl:317 [inlined]
│  [8] include_relative(::Module, ::String) at .\loading.jl:1038
│  [9] include(::Module, ::String) at .\sysimg.jl:29
│  [10] include(::String) at .\client.jl:398
│  [11] top-level scope at none:0
│ in expression starting at C:\Users\Jack\.julia\dev\RCall\deps\build.jl:10
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v0.7\Pkg\src\Operations.jl:1068
```

**Comment by randy3k** [comment]
Try again 2815fa9

**Comment by cossio** [comment]
I think I'm hitting a similar error, but on Linux. 

```
julia> ENV["R_HOME"]
"*"

julia> using Pkg

julia> Pkg.build("RCall")
  Building CodecZlib → `~/julia_depot_cossio/packages/CodecZlib/DAjXH/deps/build.log`
  Building Conda ────→ `~/julia_depot_cossio/packages/Conda/uQitS/deps/build.log`
  Building RCall ────→ `~/julia_depot_cossio/packages/RCall/RPlFw/deps/build.log`
┌ Error: Error building `RCall`: 
│ ERROR: LoadError: R_HOME is not a directory.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at logging.jl:311
│  [3] top-level scope at /home/cossio/julia_depot_cossio/packages/RCall/RPlFw/deps/build.jl:19
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1044
│  [6] include(::Module, ::String) at ./sysimg.jl:29
│  [7] include(::String) at ./client.jl:392
│  [8] top-level scope at none:0
│ in expression starting at /home/cossio/julia_depot_cossio/packages/RCall/RPlFw/deps/build.jl:10
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1097
```

**Comment by simonbyrne** [comment]
It seems to be getting caught here:
https://github.com/JuliaInterop/RCall.jl/blob/b1a8fd73ea3ad6fb777c7ffcf35066bdcbd5612b/deps/build.jl#L31-L33

We should move the check for `Rhome == "*"` to be above that.

**Comment by haberdashPI** [comment]
I am also having this problem. It appears that the location of the R executables is not the same on a windows machine. The build script is looking for the binaries in `C:\Users\david\.julia\conda\3\Library\bin\R`, while the executables are actually in `C:\Useres\david.julia\conda\3\Lib\R\bin` (and a number of other aliases as well).

**Comment by simonbyrne** [comment]
> The build script is looking for the binaries in `C:\Users\david\.julia\conda\3\Library\bin\R`, while the executables are actually in `C:\Useres\david.julia\conda\3\Lib\R\bin` (and a number of other aliases as well).

@stevengj do you know why the Conda-installed R binary wouldn't be in `Conda.BINDIR`, but in a separate path?

**Comment by stevengj** [comment]
Is it in `Conda.SCRIPTDIR`, maybe?  Though that is usually for Python scripts.  (On Unix, `Conda.SCRIPTDIR == Conda.BINDIR`, but on Windows they are different.)

**Comment by simonbyrne** [comment]
It's in `joinpath(Conda.ROOTENV, "Lib", "R")`
