### ISSUE TITLE
Error building `RCall`:

### ISSUE THREAD

**Issue by animBreedTools** [JuliaInterop/RCall.jl#277]
I get the following when I try to install RCall on a linux machine with Fedora 14.
Julia is v0.7
R is 3.5.1

julia> Pkg.build("RCall")
WARNING: Base.Pkg is deprecated, run `using Pkg` instead
 in module Main
  Building CodecZlib → `~/.julia/packages/CodecZlib/DAjXH/deps/build.log`
  Building Conda ────→ `~/.julia/packages/Conda/uQitS/deps/build.log`
  Building RCall ────→ `~/.julia/packages/RCall/Q4n8R/deps/build.log`
┌ Error: Error building `RCall`: 
│ ERROR: LoadError: Fail to use R at /opt/ghpc/R-3.5.1/lib64/R.
│ Stacktrace:
│  [1] error(::String) at ./error.jl:33
│  [2] top-level scope at logging.jl:329
│  [3] top-level scope at /usr/home/qgg/emre/.julia/packages/RCall/Q4n8R/deps/build.jl:19
│  [4] include at ./boot.jl:317 [inlined]
│  [5] include_relative(::Module, ::String) at ./loading.jl:1038
│  [6] include(::Module, ::String) at ./sysimg.jl:29
│  [7] include(::String) at ./client.jl:398
│  [8] top-level scope at none:0
│ in expression starting at /usr/home/qgg/emre/.julia/packages/RCall/Q4n8R/deps/build.jl:10
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v0.7/Pkg/src/Operations.jl:1068

**Comment by animBreedTools** [comment]
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`R RHOME`/lib"

fixed the issue

**Comment by animBreedTools** [comment]
I just re-opened a Julia session, and not working again.

ERROR: InitError: error compiling __init__: error compiling initEmbeddedR: could not load library "/opt/ghpc/R-3.5.1/lib64/R/lib/libR.so"
libRblas.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:627
 [2] macro expansion at ./logging.jl:312 [inlined]
 [3] _require_search_from_serialized(::Base.PkgId, ::String) at ./loading.jl:698
 [4] _require(::Base.PkgId) at ./loading.jl:931
 [5] require(::Base.PkgId) at ./loading.jl:852
 [6] macro expansion at ./logging.jl:311 [inlined]
 [7] require(::Module, ::Symbol) at ./loading.jl:834
during initialization of module RCall

**Comment by simonbyrne** [comment]
How did you install Julia and R?

**Comment by animBreedTools** [comment]
It is a cluster, unfortunately I have no idea how they did it.

**Comment by simonbyrne** [comment]
In that case, try the various things here: http://juliainterop.github.io/RCall.jl/stable/installation.html#Other-methods-1

**Comment by animBreedTools** [comment]
Thanks you.
I think we are close to the solution.
Now if I use the front-end machine (Julia sth.jl), I can use it. But, if I send the same job in a job file i get

ERROR: InitError: error compiling init: error compiling initEmbeddedR: could not load library "/opt/ghpc/R-3.5.1/lib64/R/lib/libR.so"
libRblas.so: cannot open shared object file: No such file or directory
