### ISSUE TITLE
R""" block giving "syntax: incomplete: invalid string syntax"

### ISSUE THREAD

**Issue by kool7d** [JuliaInterop/RCall.jl#280]
R" [code] " works fine, but R""" code blocks do not. 
For example:
R"""
modes <- nma(read.all(pdbs))
"""
gives me a string syntax error

**Comment by palday** [comment]
I can't reproduce this on the current release, so I'm going to treat this as stale. If you have an MWE on a recent release  (preferably an MWE without needing external data/packages), then please feel free to re-open
