### ISSUE TITLE
RCall prints R output to command line when calling R package

### ISSUE THREAD

**Issue by gtollefson** [JuliaInterop/RCall.jl#286]
Is it possible to suppress printing the text from the R command line REPL when calling an R package from Julia? I'm using RCall in a Julia command line tool and the printed text is a little messy.

**Comment by randy3k** [comment]
You could put a semi colon at the end to avoid printing the returned object

**Comment by gtollefson** [comment]
@randy3k I'm having some trouble with this. I've tried both:

`reval("

    library(heatmaply);

    heatmaply(x)

    ")
`

and also 

`reval("

    library(heatmaply)

    heatmaply(x)

    ");
`

Both do not suppress printing the returned object. Do you see anything I am doing wrong?

**Comment by Non-Contradiction** [comment]
The way Randy suggests can suppress the returned object, so julia won't display the returned RObject. But it doesn't deal with the package startup message displayed by R.
To suppress the package startup message, you need `suppressPackageStartupMessages` in R, or you can use `Suppressor.jl` in julia. So the solution is:
```
julia> using RCall
 
julia> using Suppressor

julia> @suppress reval("library(heatmaply);");
```
or
```
julia> using RCall

julia> reval("suppressPackageStartupMessages(library(heatmaply))");
```

**Comment by gtollefson** [comment]
@Non-Contradiction This worked well. Sorry for the late reply. Thanks to you and @randy3k.
