### ISSUE TITLE
Wrapping R pacakges

### ISSUE THREAD

**Issue by rofinn** [JuliaInterop/RCall.jl#287]
It looks like RCall is designed more for REPL usage rather than wrapping packages (e.g., no equivalent to `pyimport_conda`). Is it currently possible to safely wrap an R package in a julia package without running into precompilation issues?

**Comment by randy3k** [comment]
Could you help me understanding how `pyimport_conda` is related to the precompilation issues?

**Comment by randy3k** [comment]
The mechanism of `rimport` and `pyimport` are a bit different. `pyimport` returns a python object while `rimport` returns a julia module which is more or less the `pywrap` function of PyCall.jl.


You might try this.
```julia
module HelloWorld
using RCall
import RCall: rimport


MASS = Ref{Module}()

function __init__()
    MASS[] = rimport("MASS")
end

end # module

```

```julia
julia> import HelloWorld

julia> HelloWorld.MASS[].ginv([2 1; 0 1])
RCall.RObject{RCall.RealSxp}
              [,1] [,2]
[1,]  5.000000e-01 -0.5
[2,] -5.551115e-17  1.0
```

**Comment by randy3k** [comment]
Another possibility is to ultilize an empty RObject.

```julia
module HelloWorld
using RCall
import RCall: RObject, EnvSxp, reval_p


MASS = RObject{EnvSxp}()

function __init__()
    MASS.p = reval_p("asNamespace('MASS')")
end

end # module

```

In this way, you will have the control of the namespace of the R library.

**Comment by rofinn** [comment]
Awesome, thanks!

**Comment by palday** [comment]
@rofinn if you're satisfied, you can close the issue. :smile:
