### ISSUE TITLE
Segfault from error in function callback

### ISSUE THREAD

**Issue by Non-Contradiction** [JuliaInterop/RCall.jl#294]
```
julia> using RCall

julia> RObject(sqrt)(2)
RObject{RealSxp}
[1] 1.414214

julia> RObject(sqrt)(1:100)
Segmentation fault: 11
```

**Comment by randy3k** [comment]
Likely it is because the arguments are not protected. https://github.com/JuliaInterop/RCall.jl/blob/master/src/language.jl#L14

**Comment by randy3k** [comment]
I have looked into more thoroughly. It is expected to fail because it is basically
```
sqrt(collect(1:100))
```
However, not sure why it doesn't raise an error and makes a segfault.

**Comment by randy3k** [comment]
The segfault is caused by this line https://github.com/JuliaInterop/RCall.jl/blob/2d9bb75908d4e1be73766c7375953bd2a2659055/src/callback.jl#L62

We cannot use `Rf_error` here because it will cause longjmp.

**Comment by Non-Contradiction** [comment]
Yes, I remember that I used a similar approach in `JuliaCall` at https://github.com/Non-Contradiction/JuliaCall/blob/e841858076e67ea94646350d370e47bfef95314b/inst/julia/setup.jl#L102-L107 to avoid segmentation caused by Julia error, and there are also some simple tests in `JuliaCall` for the error handling.
