### ISSUE TITLE
Build problem: LoadError: UndefVarError: different not defined  -- missing libR.so

### ISSUE THREAD

**Issue by jeback1** [JuliaInterop/RCall.jl#297]
I'm pointing this out in the hopes that it might make it easier for the next person who makes the same mistake I made.

I tried to install RCall on Linux. I had built R myself but had not built the shared library.  Installing RCall failed with the less-than-obvious message 'ERROR: LoadError: UndefVarError: different not defined'.  

Thank you for creating RCall.  I appreciate your willingness to share this valuable tool.

**Comment by rna1990** [comment]
I had the very same issue today while building RCall. 
Thanks in advance to the RCall team for their support.

**Comment by simonbyrne** [comment]
Problem appears to be this line:
https://github.com/JuliaInterop/RCall.jl/blob/08917de58017eda73499e781dfa468236485da76/deps/build.jl#L46

**Comment by haberdashPI** [comment]
I'm lost... how does this fix the error? The variable `different` is still not defined in the build file. I'm getting this error when building RCall using Conda.
