### ISSUE TITLE
ERROR: Unsatisfiable requirements detected for package DebuggerFramework [67417a49]:

### ISSUE THREAD

**Issue by rna1990** [JuliaInterop/RCall.jl#303]
Hi.
I'm trying to reinstall RCall and I'm getting an error message because of an allegedly outdated package called DebuggerFramework:

(v1.1) pkg> add https://github.com/JuliaInterop/RCall.jl
  Updating registry at `C:\Users\rodrigo.nava\.julia\registries\General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/JuliaInterop/RCall.jl`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package DebuggerFramework [67417a49]:
 DebuggerFramework [67417a49] log:
 ├─possible versions are: 0.1.0-0.1.2 or uninstalled
 ├─restricted by compatibility requirements with Atom [c52e3926] to versions: 0.1.0-0.1.2
 │ └─Atom [c52e3926] log:
 │   ├─possible versions are: [0.1.0-0.1.1, 0.2.0-0.2.1, 0.3.0, 0.4.0-0.4.6, 0.5.0-0.5.10, 0.6.0-0.6.17, 0.7.0-0.7.15, 0.8.0-0.8.2] or uninstalled
 │   └─restricted to versions 0.7.14 by an explicit requirement, leaving only versions 0.7.14
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

**Comment by nalimilan** [comment]
This sounds related to Atom or DebuggerFramework, not RCall. Try updating or reinstalling these packages.
