### ISSUE TITLE
Could not import StatsModels.Formula

### ISSUE THREAD

**Issue by Rosenguyen0411** [JuliaInterop/RCall.jl#313]
Hi. I am very new to Julia. I was trying to install and use RCall but kept getting this error. 

Pkg.test("RCall")

WARNING: could not import StatsModels.Formula into RCall
ERROR: LoadError: LoadError: UndefVarError: Formula not defined

I use Julia v1.1.1. I spent a whole day trying to figure out where it went wrong but no luck. Any help would be greatly appreciated. Thanks a lot.

**Comment by kleinschmidt** [comment]
This is because StatsModels just made a breaking release and RCall needs to be updated.  Some discussion of how to do this in #306 

You can fix this locally by pinning StatsModels at 0.5.0 with `] add StatsModels@0.5`.

**Comment by Rosenguyen0411** [comment]
It works now. Thank you so much! You save my day!
