### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaInterop/RCall.jl#316]
Now that https://github.com/JuliaInterop/RCall.jl/pull/315 is merged, could we tag a new release of RCall.jl?

**Comment by kleinschmidt** [comment]
There shouldn't be a need to since JuliaRegistries/General#1611 caps all previously tagged versions.  The Project.toml changes here only affect future releases.

**Comment by DilumAluthge** [comment]
You are correct - I opened this issue before I saw https://github.com/JuliaRegistries/General/pull/1611, and then I forgot to close this issue
