### ISSUE TITLE
Error while building RCall

### ISSUE THREAD

**Issue by JKPH** [JuliaInterop/RCall.jl#318]
`using RCall` returns

`
ERROR: LoadError: RCall not properly installed. Please run Pkg.build("RCall")`

`Pkg.build("RCall")` returns

```
julia> Pkg.build("RCall")
  Building Conda → `C:\Users\jke4\.julia\packages\Conda\kLXeC\deps\build.log`
  Building RCall → `C:\Users\jke4\.julia\packages\RCall\iojZI\deps\build.log`
┌ Error: Error building `RCall`:
│ ERROR: LoadError: IOError: stat: invalid argument (EINVAL)
│ Stacktrace:
│  [1] stat(::String) at .\stat.jl:68
│  [2] isfile at .\stat.jl:303 [inlined]
│  [3] validate_libR(::String, ::Bool) at C:\Users\jke4\.julia\packages\RCall\iojZI\deps\setup.jl:12
│  [4] locate_libR(::String, ::Bool) at C:\Users\jke4\.julia\packages\RCall\iojZI\deps\setup.jl:53
│  [5] top-level scope at C:\Users\jke4\.julia\packages\RCall\iojZI\deps\build.jl:48
│  [6] include at .\boot.jl:326 [inlined]
│  [7] include_relative(::Module, ::String) at .\loading.jl:1038
│  [8] include(::Module, ::String) at .\sysimg.jl:29
│  [9] include(::String) at .\client.jl:403
│  [10] top-level scope at none:0
│ in expression starting at C:\Users\jke4\.julia\packages\RCall\iojZI\deps\build.jl:10
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.1\Pkg\src\Operations.jl:1075
```

`Julia v"1.1.0`
`RCall v"0.13.3"`

Issue asked on [StackOverflow here](https://stackoverflow.com/questions/56838305/fail-to-install-rcall-julia-package?noredirect=1#comment100237932_56838305)

**Comment by simonbyrne** [comment]
Do you have R installed, or are you trying to build with Conda?

**Comment by simonbyrne** [comment]
If you're trying to use Conda on Windows, I suspect #269 is the problem.

**Comment by JKPH** [comment]
I've tried both
I've tried with my own R installed and setting system environment variable R_HOME to `C:\R-3.6.0`.
I've also tried forcing conda installing it by either removing my R distrib and setting my R_HOME to `*`

**Comment by JKPH** [comment]
I've been reading #269 and it seems that `joinpath(Conda.ROOTENV, "Lib", "R") = "C:\\Users\\jke4\\.julia\\conda\\3\\Lib\\R"` is not a valid path for me.

`"C:\\Users\\jke4\\.julia\\conda\\3\\Lib"` is

**Comment by JKPH** [comment]
Alright it looks like
`] pin RCall@0.12.1`
Forcing RCall to use one of its previous version does work for me and I am now able to run my code calling R.

**Comment by simonbyrne** [comment]
Conda R on Windows requires some funny PATH business I'm still trying to figure out.

what message do you get if you don't set `R_HOME`?

**Comment by JKPH** [comment]
Well now it works well! Did you change something?
