### ISSUE TITLE
DataFrames 0.19: deprecated syntax 

### ISSUE THREAD

**Issue by pfarndt** [JuliaInterop/RCall.jl#321]
Recently, I get a lot of warnings like:
```
Warning: `getindex(df::DataFrame, col_ind::ColumnIndex)` is deprecated, use `df[!, col_ind]`
```
when trying to return a R data.frame to Julia. AFAIK some DataFrame methods will be deprecated at some point.

**Comment by ppalmes** [comment]
related to PR https://github.com/JuliaInterop/RCall.jl/pull/327

**Comment by ppalmes** [comment]
can be close now
