### ISSUE TITLE
Bug: segfault when using ggplot

### ISSUE THREAD

**Issue by greimel** [JuliaInterop/RCall.jl#335]
This works

```julia
using RCall
R"""
library(ggplot2)

df = data.frame(pcchange=c(0.8, 0.6, 1.6, 0.05), experiment=
             c("Ineq", "Ineq", "SG", "SG"), variable = c("d2y", "p", "d2y", "p"))

ggplot(df) + geom_bar(aes(x=variable, y=pcchange), stat="identity", position="dodge")
"""
```

Using the `fill` aesthetic segfaults (similar for `color`):

```julia
using RCall
R"""
library(ggplot2)

df = data.frame(pcchange=c(0.8, 0.6, 1.6, 0.05), experiment=
             c("Ineq", "Ineq", "SG", "SG"), variable = c("d2y", "p", "d2y", "p"))

ggplot(df) + geom_bar(aes(x=variable, y=pcchange, fill=experiment), stat="identity", position="dodge")
"""
```

Code works in the R console.

**Comment by hsm207** [comment]
Seems to be fixed with Julia version 1.3.1 and RCall 0.13.5. I got the following output:

![image](https://user-images.githubusercontent.com/2398765/75607585-afda4b00-5b33-11ea-8c94-62030adb193a.png)

**Comment by greimel** [comment]
for me this still segfaults. I am on Ubuntu 18,04, Julia 1.4, RCall 13.6

I had given up on this workflow because I got segfaults quite often. Now that I tried again, nothing has changed.

For example (sorry, no MWE)

```julia
# this works
ggplot(df) + geom_line(aes(x=:x, y=:y, color=:col)) + facet_wrap(R" ~ y_lay", scale="free_y")

# this segfaults (added `~ x_lay`)
ggplot(df) + geom_line(aes(x=:x, y=:y, color=:col)) + facet_wrap(R"x_lay ~ y_lay", scale="free_y")

# this also segfaults (added `scale_y_log10()` instead)
ggplot(df) + geom_line(aes(x=:x, y=:y, color=:col)) + facet_wrap(R" ~ y_lay", scale="free_y") + scale_y_log10()
```

**Comment by greimel** [comment]
i made RCall reinstall R with

```julia
ENV["R_HOME"] = "*"
using Pkg
Pkg.build("RCall")
```

and now it works. No more segfaults :-)

**Comment by hsm207** [comment]
Looks like the problem could have been an old version of R.

Anyway, if you are using RCall because of ggplot, I found [Gadfly](https://github.com/GiovineItalia/Gadfly.jl) to be the perfect substitute.
