### ISSUE TITLE
Automatic installation of R fails

### ISSUE THREAD

**Issue by mbauman** [JuliaInterop/RCall.jl#336]
I'm not sure if this is a docs bug or an actual bug, but according to the docs things should just work with `R_HOME` either unset or set to `""`.  That's not the case for me:

```juila
julia> ENV["R_HOME"]
ERROR: KeyError: key "R_HOME" not found

(r-interop) pkg> add RCall
...
  Building Conda → `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building RCall → `~/.julia/packages/RCall/g7dhB/deps/build.log`
┌ Error: Error building `RCall`:
│ ERROR: LoadError: R_HOME is not a directory.
...

julia> ENV["R_HOME"] = ""
""

(r-interop) pkg> build RCall
  Building Conda → `~/.julia/packages/Conda/kLXeC/deps/build.log`
  Building RCall → `~/.julia/packages/RCall/g7dhB/deps/build.log`
┌ Error: Error building `RCall`:
│ ERROR: LoadError: R_HOME is not a directory.
...
```

It finally works with the `R_HOME` set to `"*"`.  

I know there are a lot of install issues open, but I didn't see anything along these lines.  I'm using Julia 1.2 on macOS 10.14.

**Comment by simonbyrne** [comment]
There is some work on this in #311

**Comment by simonbyrne** [comment]
I don't really have time to do this any more, so if anyone else is interested in taking on maintenance, I would be grateful.

**Comment by palday** [comment]
I think this is stale/solved by now, but if not, please feel free to open a new issue.
