### ISSUE TITLE
Malformed factor when converting DataFrames with categoricals

### ISSUE THREAD

**Issue by jmboehm** [JuliaInterop/RCall.jl#349]
Is the following behaviour to be expected?

On Julia 1.3.0 with RCall 0.13.4 and DataFrames 0.19.4, and R 3.5.2:
```julia
using Random, DataFrames, RCall
rng = MersenneTwister(1234)
a = rand(rng, 1:10, 10)
df_a = DataFrame(a = categorical(a))
@rput df_a
R"df_a"
```
yields
```
RObject{VecSxp}
Error showing value of type RObject{VecSxp}:
ERROR: REvalError: Error in as.character.factor(x) : malformed factor
```

**Comment by nalimilan** [comment]
#332 fixes this. But note that since R factors can only have string levels, the result won't be exactly the same as in Julia: use `categorical(string.(a))` for that.
