### ISSUE TITLE
Using RCall hangs on Julia 1.4.1 and 1.3.1

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaInterop/RCall.jl#359]
I just installed RCall.jl and to be safe I `]build RCall`

Now `using RCall` just hangs but shows the R initialization print outs

Gets stuck here. I am on Windows 10. 

![image](https://user-images.githubusercontent.com/4497189/79691816-f5e69c00-82a4-11ea-8826-512eeb5d8385.png)

**Comment by randy3k** [comment]
@xiaodaigh would you check again with the master branch? It should be working now.

**Comment by xiaodaigh** [comment]
working now thanks.
