### ISSUE TITLE
Unable to interrupt with ctrl+C when RCall is used

### ISSUE THREAD

**Issue by asasa137** [JuliaInterop/RCall.jl#369]
Hello everybody,

I am unable to perform an InterruptException with ctrl+c after perfoming `using RCall` (or import ` RCall`)

To test :
```
for i in 1:10
       println(i);
       sleep(1)
end
using RCall
for i in 1:10
       println(i);
       sleep(1)
end
```

In the first loop, when I do ctrl+c, the execution is stopped.
In the second, I can't stop the loop before its end.

I am on Julia Version 1.4.0 (2020-03-21)

Thanks,

Axel

**Comment by randy3k** [comment]
Are you on windows?

**Comment by randy3k** [comment]
I just notice recently while working on [`rchitect`](https://github.com/randy3k/rchitect) that the function [`Rf_initialize_R`](
https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/gnuwin32/embeddedR.c#L119) function on windows will set a signal handler on windows.

Basically, we need to mirror that function without `signal(...)`.

**Comment by asasa137** [comment]
I forgot to mention, sorry... I am well on windows.
Great that know how to handle the problem!
