### ISSUE TITLE
Set SSH deploy key for TagBot

### ISSUE THREAD

**Issue by randy3k** [JuliaInterop/RCall.jl#375]
As shown in https://github.com/JuliaRegistries/TagBot/blob/master/README.md#ssh-deploy-keys

I don’t have the necessary permission to set up the key.

**Comment by randy3k** [comment]
@nalimilan or @simonbyrne ?

**Comment by nalimilan** [comment]
Actually you don't *need* to set up SSH keys. Just creating the GitHub Action as shown in the first part of the README is enough.

**Comment by nalimilan** [comment]
Hmm, at https://github.com/JuliaInterop/RCall.jl/actions?query=workflow%3ATagBot I see that TagBot runs have succeeded, and at https://github.com/JuliaInterop/RCall.jl/releases I see a release from two days ago, so what's the problem? :-)

**Comment by randy3k** [comment]
> The most notable reason is that the default token does not have permission to trigger events for other GitHub Actions, such as documentation builds for new tags.


That doesn’t trigger documentation.

**Comment by nalimilan** [comment]
Ah. I'm surprised by this quote, as for CategoricalArrays I haven't added tokens AFAIK yet the manual has a page for 0.8.0. Maybe that refers to something else?

**Comment by randy3k** [comment]
I am quite sure that is true. It happens to my personal repos.

**Comment by nalimilan** [comment]
Ah CategoricalArrays deploys documentation from Travis but RCall does that from GitHub Actions. Maybe that's the reason for the difference.

**Comment by nalimilan** [comment]
@ararslan Since you're an owner, could you have a look?

**Comment by simonbyrne** [comment]
@randy3k @nalimilan: I've made you both owners.

**Comment by randy3k** [comment]
Thanks @simonbyrne
