### ISSUE TITLE
Example doesn't work for all RDataset versions

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaInterop/RCall.jl#384]
E.g. not for whatever verion I had installed, nor for recent (lots of errors):

```
(@v1.5) pkg> add RDatasets#v0.6.5
```
But RDatasets#v0.6.5 (currently) latest works, so I considered a PR to README, adding:

```
using RDatasets  # e.g. verson 0.6.7 works
```

You would think since the latest works, it would stay that way, but seeing ggplot.png is 4 years old, it seems later versions broke and fixed, and could happen again. Most uses should know to use latest, but may not know, and blame your package, and you really do not want that package as a dependency with version bounds.

**Comment by randy3k** [comment]
As far as I know, the current version of RCall depends on DataFrame.jl v0.21 but RDatasets.jl doesn't support it.

**Comment by PallHaraldsson** [comment]
There's no big problem, i.e. it does work with latest RDatasets.jl. I'm just saying, for newbies, if you have it installed, like I did, and it's not up to date, as you do not have a dependency, your example will not work (until you figure out and update).
