### ISSUE TITLE
Time-sensitive: migrate from Travis-CI.org to Travis-CI.com

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaInterop/RCall.jl#391]
Currently, RCall.jl uses Travis-CI.org.

Travis-CI.org will be shut down on December 31, 2020: https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom?e=%5BUNIQID%5D

Therefore, before then, we need to migrate from Travis-CI.org to Travis-CI.com.

The migration needs to be performed by a user that is an `owner` of the relevant GitHub organization, which in this case is JuliaInterop.

Instructions for migration are available here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration

**Comment by palday** [comment]
Even worse: Travis as a whole seems to drastically cutting support for FOSS, with several reports indicating that they won't even give credits when asking nicely (e.g. [here](https://twitter.com/james_hilliard/status/1336081776691843072)), so we should probably migrate to GitHub Actions. The tricky bit for RCall is having both R and Julia available in the environment, but I have a mostly working solution as part of [JellyMe4](https://github.com/palday/JellyMe4.jl/pull/42/). I'll open a PR here in a few days with the fix: the basic setup is pretty straightforward, but I'll probably need help getting Conda and Coveralls working perfectly. Note that my testing so far has indicated that the old `GLIBCXX` issue (#339) is particularly tricky to solve on GH Actions, but it is very easy to set up one CI that does Windows, Mac and Linux once you get that solved.
