### ISSUE TITLE
Feature request: when using Conda to install R, add the ability to specify the version of R that Conda installs

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaInterop/RCall.jl#393]
This should be relatively straightforward to implement, e.g. something like this in the `deps/build.jl` file:

```julia
Rhome = get(ENV, "R_HOME", "")
if Rhome == "*"
    r_version = get(ENV, "RCALL_CONDA_R", ">=3.4.0,<4")
    Conda.add("r-base$(r_version)")
end
```

Then, you can override the version of R installed by Conda by setting `RCALL_CONDA_R`, e.g.:
```julia
ENV["RCALL_CONDA_R"] = ">=3.6.0,<4"
```

```julia
ENV["RCALL_CONDA_R"] = "=3.5"
```

**Comment by palday** [comment]
I'm marking this as stale/not planned, because we now have experimental CondaPkg support, where this can be specified via CondaPkg's dependency file.

That said, if somebody wants to open a PR with the necessary changes, I would be happy to revirew.
