### ISSUE TITLE
In Jupyter notebook, how to deal with the R function argument that contain special symbol?

### ISSUE THREAD

**Issue by zhanglab2008** [JuliaInterop/RCall.jl#424]
Hi, great work!
I don't know how to escape the special character in the arguments when I used RCall in jupyter notebook. Here is an example:
```bash
@rimport Seurat as seu
seu.DimPlot(object=R"girlom", label=true, label.size=6)
```
In this example, label.size has a special symbol ".", which is allowed in R. When I run this in Julia, however, it gets me this error:
```bash
syntax: invalid keyword argument name "label.size" around In[19]:1

Stacktrace:
 [1] top-level scope
   @ In[19]:1
 [2] eval
   @ ./boot.jl:360 [inlined]
 [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1094
```
Do you have any ideas how to get around this?
Many thanks!!!

**Comment by randy3k** [comment]
See bottom of the page https://juliainterop.github.io/RCall.jl/stable/gettingstarted/#@rlibrary-and-@rimport-macros-1

**Comment by zhanglab2008** [comment]
Thank you so much!!!
