### ISSUE TITLE
Problems after updating R

### ISSUE THREAD

**Issue by DavidVJS** [JuliaInterop/RCall.jl#435]
I recently updated my R installation from 3.5.2 to 4.1.1 and am having issues updating Rcall. I set the environment variable as instructed
ENV["R_HOME"] = "C:/Program Files/R/R-4.1.1"
Pkg.build("RCall")
but when I try to use RCall I get an error referring to the previous path
InitError: Could not find library C:\Program Files\R\R-3.5.1\bin\x64\R.dll.

Removing RCall using Pkg.rm("RCall") before reinstalling doesn't help.  Putting R_HOME in PATH doesn't help.  Deleting the pre-compiled RCall files in .julia/compiled/v1.6/RCall doesn't help.  This is a standard, single user R installation under windows 10.  Deleting the registry entries for the old version of R doesn't help.  Clearly RCall is still looking for the old version, but I have no idea where the old reference is coming from.

**Comment by terasakisatoshi** [comment]
@DavidVJS 

Try to modify `ENV["R_HOME"]`

from 

```
ENV["R_HOME"] = "C:/Program Files/R/R-4.1.1"
```

to

```
ENV["R_HOME"] = "C:\\Program Files\\R\\R-4.1.1"
```
