### ISSUE TITLE
ERROR: Could not determine command

### ISSUE THREAD

**Issue by liamblything1** [JuliaInterop/RCall.jl#437]
I was able to add RCall into the Julia interface, but  

when I wrote in the following:
**(@v1.6) pkg> using RCall**

I got the error:
ERROR: Could not determine command

**Comment by simonbyrne** [comment]
use `add RCall` at the package prompt to add it to the project, `using RCall` at the julia prompt to load it.

See https://docs.julialang.org/en/v1/stdlib/Pkg/
