### ISSUE TITLE
Is RCall known not to work on M1 Macs?

### ISSUE THREAD

**Issue by awellis** [JuliaInterop/RCall.jl#440]
I get this error message on loading `RCall`:

```
ERROR: InitError: cfunction: closures are not supported on this platform
```

Installation was fine on Julia 1.7.1, MacOS 12.1 

```
Julia Version 1.7.1
Commit ac5cc99908 (2021-12-22 19:35 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.2.0)
  CPU: Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, cyclone)
```

**Comment by awellis** [comment]
What does this mean for RCall on Apple Silicon? Is M1 support on the roadmap?

**Comment by simonbyrne** [comment]
The upstream issue in Julia is https://github.com/JuliaLang/julia/issues/27174

Alternatively, it may be possible to switch RCall.jl to use non-closure cfunctions. There isn't a concrete roadmap, but pull requests are always welcome!
