### ISSUE TITLE
Trouble while trying to install RCall package

### ISSUE THREAD

**Issue by josh3397** [JuliaInterop/RCall.jl#449]
Hi,

I'm trying to install RCall package inside Julia using command Pkg.build("RCall") after setting the path for environment variable R_HOME. I run into following issue. 
Error building `RCall`: 
ERROR: LoadError: Could not find library /users/joshimuk/R/lib/libR.so. Make sure that R shared library exists.

Can you please help me how can solve this issue?

Thanks!

**Comment by ViralBShah** [comment]
This is because RCall is unable to find your R installation, despite setting R_HOME. Perhaps discourse is a better place to ask, if this is still an issue.
