### ISSUE TITLE
Segfault and Unknown Function

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaInterop/RCall.jl#451]
Right now running into an unknown error as follows when I try to do the following:

```julia
using RCall

R"""
remotes::install_github("OHDSI/Eunomia")
library("Eunomia")
"""
```

which gives this error:

```
signal (11): Segmentation fault: 11
in expression starting at REPL[3]:1
unknown function (ip: 0x16260162d)
Allocations: 12470194 (Pool: 12465629; Big: 4565); GC: 15
```

I do not know what this means but I provided as much information as possible as follows:

RCall version: v0.13.12

R information (installed via Conda.jl using RCall's installation method):

```
               _
platform       x86_64-apple-darwin13.4.0
arch           x86_64
os             darwin13.4.0
system         x86_64, darwin13.4.0
status
major          3
minor          6.1
year           2019
month          07
day            05
svn rev        76782
language       R
version.string R version 3.6.1 (2019-07-05)
nickname       Action of the Toes
```

Julia information

```
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.5.0)
  CPU: Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = nvim
```

OS information:

```
OS: macOS Catalina 10.15.7 19H1715 x86_64
Host: MacBookPro16,3
Kernel: 19.6.0
Uptime: 37 days, 19 hours, 30 mins
Packages: 241 (brew)
Shell: zsh 5.7.1
Resolution: 1440x900@2x
DE: Aqua
WM: Amethyst
Terminal: tmux
CPU: Intel i5-8257U (8) @ 1.40GHz
GPU: Intel Iris Plus Graphics 645
Memory: 13461MiB / 16384MiB
```

Thank you!

**Comment by TheCedarPrince** [comment]
Oh and also to be clear, the package loads fine in R itself so I do not think that R is to blame here but something going on with Julia + R interop...

**Comment by Non-Contradiction** [comment]
Investigate a little more into the problem. Hope the information helps. 

The package Eunomia has package DatabaseConnector in its Depends, so loading Eunomia will trigger the loading of DatabaseConnector automatically in R. And loading DatabaseConnector will also trigger the segfault error. 

Checking `DatabaseConnector:::.onLoad` in R, I see that the function (which will be triggered automatically in R when loading the package) will trigger the loading of some java package using rJava. And the loading of java package in rJava will trigger `rJava::.jinit`. And it is the `rJava::.jinit`that causes the segfault error.

I think it is that the Julia + R interop somehow messes with the Java + R interop. But currently, I don't know how to deal with the problem.

**Comment by Non-Contradiction** [comment]
A temporary "solution" I found is that one can invoke Java + R interop before the Julia + R interop.
For example, using the JuliaCall package in R, I have 
````
> rJava::.jinit()
> JuliaCall::julia_command('R"library(Eunomia)"')
Julia version 1.7.3 at location /Users/Sean/Library/Application Support/org.R-project.R/R/JuliaCall/julia/1.7.3/Julia-1.7.app/Contents/Resources/julia/bin will be used.
Loading setup script for JuliaCall...
Finish loading setup script for JuliaCall.
[1] "Eunomia"           "DatabaseConnector" "stats"             "graphics"         
[5] "grDevices"         "utils"             "datasets"          "methods"          
[9] "base"             
RObject{StrSxp}
````

**Comment by TheCedarPrince** [comment]
Hey @Non-Contradiction !
I had found this workaround too!
It seems that if one loses a problematic R package within the R REPL first and then create the Julia + R interop, things are properly loaded and nothing bad happens.
Not sure as to why, but we can close this issue.
