### ISSUE TITLE
error in install 'Rcall'.

### ISSUE THREAD

**Issue by Galaxy-228** [JuliaInterop/RCall.jl#453]
Hi:
I was met the error following:
![图片](https://user-images.githubusercontent.com/53716512/184785586-fc72e592-8730-47ba-b7ac-de049a9f6779.png)
Thamnks so much!

**Comment by digital-carver** [comment]
Hi, 

That looks like just a download issue. Try the `Pkg.build("RCall")` again, and check if access to https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh is being blocked because of a firewall.

**Comment by Galaxy-228** [comment]
Thanks so much for your reply.
I have met another error followed:
![图片](https://user-images.githubusercontent.com/53716512/186047524-f84fe627-af10-4200-b189-ef44ae2f1be6.png)
Thanks so much !

**Comment by digital-carver** [comment]
Hi, 

That looks like an issue with a completely different package. You can post that on https://discourse.julialang.org/ along with a description of what your code is trying to do, and ask for assistance there. 

If you're able to build `RCall` succesfully now, you can close this issue and take further discussions to https://discourse.julialang.org/.

**Comment by Galaxy-228** [comment]
Hi,
Thanks so much for
