### ISSUE TITLE
Windows CI cannot find R shared library on x86

### ISSUE THREAD

**Issue by ViralBShah** [JuliaInterop/RCall.jl#458]
I am seeing these errors in the Windows CI in recent PRs (Example: https://github.com/JuliaInterop/RCall.jl/actions/runs/3277665393/jobs/5395214932#step:7:222)

```
    Building RCall → `D:\a\RCall.jl\RCall.jl\deps\build.log`
ERROR: LoadError: Could not find library C:\R\bin\i386\R.dll. Make sure that R shared library exists.
Stacktrace:
 [1] error(s::String)
   @ Base .\error.jl:35
 [2] validate_libR(libR::String)
   @ Main D:\a\RCall.jl\RCall.jl\deps\setup.jl:11
 [3] locate_libR(Rhome::SubString{String})
   @ Main D:\a\RCall.jl\RCall.jl\deps\setup.jl:43
 [4] top-level scope
   @ D:\a\RCall.jl\RCall.jl\deps\build.jl:58
 [5] include(fname::String)
   @ Base.MainInclude .\client.jl:476
 [6] top-level scope
   @ none:5
in expression starting at D:\a\RCall.jl\RCall.jl\deps\build.jl:11
ERROR: Error building `RCall`: 
```

**Comment by ViralBShah** [comment]
@DilumAluthge Might you know what is going on here? We use the R setup provided on github actions by `r-lib`.

**Comment by DilumAluthge** [comment]
I'm assuming that in CI, we should let RCall install R via Conda, instead of trying to find it on the system.

**Comment by ViralBShah** [comment]
Should we just try to disable the whole Conda R and see what happens?

**Comment by ViralBShah** [comment]
I thought that the github actions thing would set R up the right way. So perhaps either install the `r-lib` provided action or conda - but not both?

**Comment by ViralBShah** [comment]
Some discussion about the right path: https://github.com/JuliaInterop/RCall.jl/pull/459#issuecomment-1284692013

**Comment by palday** [comment]
I think this is stale/resolved now, but feel free to re-open if that's wrong!
