### ISSUE TITLE
RCall  Build Error on Mac M1

### ISSUE THREAD

**Issue by jim2236** [JuliaInterop/RCall.jl#473]
I am running Julia 1.7 on a MacBook M1 Max, Ventura 13.1.  I get the same results for Julia 1.8.  I tried building RCall but continue to get the following error message regardless of the installation method I use.  I think this is an architecture issue, but not sure it that is accurate. 

ERROR: Error building `RCall`: 
ERROR: could not load library "/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib"
dlopen(/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib, 0x0001): tried: '/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib' (no such file), '/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
ERROR: LoadError: Try adding /opt/homebrew/Cellar/r/4.2.2/lib/R/lib to the "LD_LIBRARY_PATH" environmental variable and restarting Julia.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] validate_libR(libR::String)
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:26
 [3] locate_libR(Rhome::SubString{String})
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:43
 [4] top-level scope
   @ ~/.julia/packages/RCall/Wyd74/deps/build.jl:58
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [6] top-level scope
   @ none:5
in expression starting at /Users/squeeks/.julia/packages/RCall/Wyd74/deps/build.jl:11

caused by: could not load library "/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib"
dlopen(/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib, 0x0001): tried: '/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib' (no such file), '/opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
Stacktrace:
 [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
   @ Base.Libc.Libdl ./libdl.jl:117
 [2] dlopen (repeats 2 times)
   @ ./libdl.jl:117 [inlined]
 [3] validate_libR(libR::String)
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:16
 [4] locate_libR(Rhome::SubString{String})
   @ Main ~/.julia/packages/RCall/Wyd74/deps/setup.jl:43
 [5] top-level scope
   @ ~/.julia/packages/RCall/Wyd74/deps/build.jl:58
 [6] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [7] top-level scope
   @ none:5

I've installed R before starting Julia from the CRAN package, and installed Quartz as recommended on the R webpage,  and set the LD_LIBRARY_PATH as recommended.  I set the path to opt/homebrew/Cellar/r/4.2.2/lib/R/lib/libR.dylib, and then `R RHOME`/lib.  I uninstalled that and installed R with Homebrew.  I set the LD_LIBRARY_PATH as recommended.  I continue to get the same error.   

I would appreciate help with this issue.   Thanks.

**Comment by simonbyrne** [comment]
what is your Julia `versioninfo()`?

**Comment by simonbyrne** [comment]
I suspect the issue is that you're using the Intel x86 Julia binary (via Rosetta), but the native ARM R binary. The easiest option is to switch to the native ARM Julia binary.

**Comment by jim2236** [comment]
I installed Julia 1.8.4 ARM, which did work. l can work with this.

Thank you,

**Comment by dmbates** [comment]
@jim2236 @simonbyrne Can this issue be closed?  It seems to have been resolved.

**Comment by jim2236** [comment]
Douglas,

I reinstalled Julia and solved the problem.  The issue can be closed.

Thank you
Jim Michael
