### ISSUE TITLE
RCall installation failing with ENV = "*"

### ISSUE THREAD

**Issue by MaxMenzies** [JuliaInterop/RCall.jl#482]
I'm following the instructions, ENV["R_Home"]="*" then using Pkg and Pkg.build("RCall") and getting the following error:

"ERROR: Error building `RCall`:
Warning: 'r' already in 'channels' list, moving to the top
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.

[ Info: Installing R via Conda.  To use a different R installation, set the "R_HOME" environment variable and re-run Pkg.build("RCall").
[ Info: Running `conda config --add channels r --file 'C:\Users\annoy\.julia\conda\3\x86_64\condarc-julia.yml' --force` in root environment
[ Info: Running `conda install -y 'r-base>=3.4.0,<4'` in root environment
ERROR: LoadError: Could not find library C:\Users\annoy\.julia\conda\3\x86_64\Library\bin\R\bin\x64\R.dll. Make sure that R shared library exists.
Stacktrace:"

![image](https://user-images.githubusercontent.com/62193467/224620535-ac2d0160-6fe7-440c-8d14-439b66cdd52c.png)

**Comment by frankier** [comment]
I'm not sure what happened there since there seem to be two levels of `bin`  in your R_HOME

There have been some changes to this in the newest version. Perhaps you could try again with new versions of Julia and RCall.jl and close this if it's no longer a problem?

**Comment by palday** [comment]
I'm closing this as stale, but I'm happy to re-open @MaxMenzies if you're still having problems.
