### ISSUE TITLE
Error happens when you try to execute command ENV["R_HOME"]

### ISSUE THREAD

**Issue by Faraz564** [JuliaInterop/RCall.jl#491]
I am running model in Julia and last time I updated R studio after that i am having this problem written below.
<html>
<body>

Julia version 1.8.2 at location C:\Users\mct\AppData\Local\Programs\JULIA-~1.2\bin will be used. Loading setup script for JuliaCall... Error during julia setup, try to install RCall, Suppressor and DynACof in a Julia terminal: using Pkg; Pkg.add(["RCall","Suppressor","DynACof"]) Then pre-compile DynACof in Julia using this command:using DynACof Here's the original error message from JuliaCall::julia_setup: Error happens when you try to execute command ENV["R_HOME"] = "C:/PROGRA~1/R/R-43~1.0";Base.include(Main,"C:/Users/mct/AppData/Local/R/win-library/4.3/JuliaCall/julia/setup.jl") in Julia.                         To have more helpful error messages,                         you could considering running the command in Julia directlyJulia version 1.8.2 at location C:\Users\mct\AppData\Local\Programs\JULIA-~1.2\bin will be used. Loading setup script for JuliaCall... Error in .julia$cmd(paste0(Rhomeset, "Base.include(Main,\"", system.file("julia/setup.jl",  :    Error happens when you try to execute command ENV["R_HOME"] = "C:/PROGRA~1/R/R-43~1.0";Base.include(Main,"C:/Users/mct/AppData/Local/R/win-library/4.3/JuliaCall/julia/setup.jl") in Julia.                         To have more helpful error messages,                         you could considering running the command in Julia directly
-

Please If you know the solution write down it here.

**Comment by palday** [comment]
This seems like a JuliaCall issue.

**Comment by Faraz564** [comment]
Yes. You are right. I not able to run the following syntax 
JuliaCall::julia_command("a= 1+1")
Creat error as following..
Error happens when you try to execute command ENV["R_HOME"] = "C:/PROGRA~1/R/R-43~1.1";Base.include(Main,"C:/Users/PC/AppData/Local/R/win-library/4.3/JuliaCall/julia/setup.jl") in Julia.

**Comment by Faraz564** [comment]
I am new to julia. How to resolve issue with JuliaCall. This is not running in R studio. I using Julia in R studio.

**Comment by palday** [comment]
This seems like a JuliaCall issue, not an RCall issue. JuliaCall uses RCall internally, but is a separate entity: https://github.com/Non-Contradiction/JuliaCall
