### ISSUE TITLE
libR.so in nonstandard location

### ISSUE THREAD

**Issue by kose-y** [JuliaInterop/RCall.jl#492]
In a cluster environment we use, `libR.so` is located under `$R_HOME/lib64/R/lib/`, not the standard `$R_HOME/lib/`. Is there a good way to install RCall properly in this case?

**Comment by frankier** [comment]
A current workaround is to modify the `libR` value in `deps/deps.jl`. If [my recent PR](https://github.com/JuliaInterop/RCall.jl/pull/496) lands it its current form, you would also be able to do this using the Julia Preferences system.

**Comment by frankier** [comment]
@kose-y Now that https://github.com/JuliaInterop/RCall.jl/commit/31e7859ab2757d8019b42eb18522703415ff8c85 is merged, does this solve your problem?

**Comment by kose-y** [comment]
Thanks for your amazing work. It looks like it should solve the problem.
