### ISSUE TITLE
RCall.jl failed to build with Conda (23.3.1)

### ISSUE THREAD

**Issue by szcf-weiya** [JuliaInterop/RCall.jl#497]
I encountered the error during the AutoMerge step of my package https://github.com/JuliaRegistries/General/pull/90356

Here are the error message, you can also check the full report in the GitHub action https://github.com/JuliaRegistries/General/actions/runs/5992965182/job/16252930207?pr=90356
```
[ Info: Installing R via Conda.  To use a different R installation, set the "R_HOME" environment variable and re-run Pkg.build("RCall").
[ Info: Downloading miniconda installer ...
[ Info: Installing miniconda ...
[ Info: Running `conda config --add channels r --file /tmp/jl_gaGCwn/conda/3/x86_64/condarc-julia.yml --force` in root environment
[ Info: Running `conda install -y 'r-base>=3.4.0,<4'` in root environment
ERROR: LoadError: failed process: Process(setenv(`/tmp/jl_gaGCwn/conda/3/x86_64/bin/conda install -y 'r-base>=3.4.0,<4'`,["PATH=/opt/hostedtoolcache/julia/1.9.3/x64/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin", "CONDA_PREFIX=/tmp/jl_gaGCwn/conda/3/x86_64", "***", "DISPLAY=:99", "JULIA_LOAD_PATH=@:/tmp/jl_gKdbOJ", "OPENBLAS_DEFAULT_NUM_THREADS=1", "JULIA_REGISTRYCI_AUTOMERGE=true", "XAUTHORITY=/tmp/xvfb-run.KukMkt/Xauthority", "HOME=/home/runner", "JULIA_PKG_PRECOMPILE_AUTO=0", "CONDARC=/tmp/jl_gaGCwn/conda/3/x86_64/condarc-julia.yml", "JULIA_DEPOT_PATH=/tmp/jl_gaGCwn", "OPENBLAS_MAIN_FREE=1", "R_HOME=*", "PYTHONIOENCODING=UTF-8"]), ProcessExited(1)) [1]
```

In the previous version of my package (v0.1.1) https://github.com/JuliaRegistries/General/pull/88105, all worked well. The Conda.jl is v1.9.1
In the updated version (v0.1.2), it failed but should not be related to my change from v0.1.1 to v0.1.2, and the installed Conda.jl is again v1.9.1.

I can also reproduce the same error in a docker environment (mimicking the GitHub action env) when only trying to install RCall.jl

In my opinion, the Conda version should make the difference since Conda.jl tends to install the latest Conda! Previously, the conda version is something like 23.1.x (since I tested locally although no version can be found from the GitHub action log), but now the conda is 23.3.1 (the version is also determined from my local test in the docker env)

Does anyone have some suggestions? Thanks!

**Comment by palday** [comment]
@szcf-weiya as soon as https://github.com/JuliaRegistries/General/pull/90460 is merged, can you try to restart the CI on your registration request? You can do this by commenting `@JuliaRegistrator register` again on the relevant commit.

**Comment by palday** [comment]
Ah beautiful it all worked 🎉 🚀
