### ISSUE TITLE
Unable to Pkg.build RCall

### ISSUE THREAD

**Issue by casasgomezuribarri** [JuliaInterop/RCall.jl#501]
I followed the [installation instructions](https://juliainterop.github.io/RCall.jl/stable/installation/) from the docs, and set `ENV["R_HOME"]` to my R home directory (as indicated by `R.home()` in `R`).

I then ran `Pkg.build("Rcall")` and got the following error:

> ERROR: Error building `RCall`: 
> ERROR: could not load library "/Library/Frameworks/R.framework/Resources/lib/libR.dylib"
> dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 0x0001): tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
> ERROR: LoadError: Try adding /Library/Frameworks/R.framework/Resources/lib to the "LD_LIBRARY_PATH" environmental variable and restarting Julia.
> 
> (...)
> 
> caused by: could not load library "/Library/Frameworks/R.framework/Resources/lib/libR.dylib"
> dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 0x0001): tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

How do I add the R home directory to the LD_LIBRARY_PATH environmental variable?

How can I solve those incompatibility issues? I am working from an M1 Max MacBook Pro.

**Comment by jeanpauphilet** [comment]
Hi, 

I had a similar issue recently. 
It is likely due to the fact that one of the programs (R or Julia) is not built for the right architecture. 

If you are using an  M1 Max MacBook Pro, your architecture should be ARM (aarch64 or arm64). 
You can check the architecture used by Julia by displaying the value of the Sys.ARCH constant (you should get :aarch64).
You can check the architecture used by R with the `R.version` command. 

Then, you should reinstall any program (R or Julia) that is currently not built for the right architecture, by making sure you download the right installation files.

**Comment by palday** [comment]
I think @jeanpauphilet is exactly right.

**Comment by luboshanus** [comment]
I still obtain same error as above on M3 MacBook and Julia LTS `1.6.7`.  
```julia
(@v1.6) pkg> st
      Status `~/.julia/environments/v1.6/Project.toml`
...
  [6f49c342] RCall v0.14.1
```

It works with Julia 1.8.5 and 1.10.2.

But the error is:

```
(@v1.6) pkg> build
    Building Conda ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/51cab8e982c5b598eea9c8ceaced4b58d9dd37c9/build.log`
    Building IJulia → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/47ac8cc196b81001a711f4b2c12c97372338f00c/build.log`
    Building RCall ─→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/846b2aab2d312fda5e7b099fc217c661e8fae27e/build.log`
ERROR: Error building `RCall`: 
ERROR: could not load library "/Library/Frameworks/R.framework/Resources/lib/libR.dylib"
dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 0x0001): tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
ERROR: LoadError: Try adding /Library/Frameworks/R.framework/Resources/lib to the "LD_LIBRARY_PATH" environmental variable and restarting Julia.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] validate_libR(libR::String)
   @ Main ~/.julia/packages/RCall/dDAVd/deps/setup.jl:26
 [3] top-level scope
   @ ~/.julia/packages/RCall/dDAVd/deps/build.jl:20
 [4] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [5] top-level scope
   @ none:5
in expression starting at /Users/luboshanus/.julia/packages/RCall/dDAVd/deps/build.jl:11

caused by: could not load library "/Library/Frameworks/R.framework/Resources/lib/libR.dylib"
dlopen(/Library/Frameworks/R.framework/Resources/lib/libR.dylib, 0x0001): tried: '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libR.dylib' (no such file), '/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
Stacktrace:
 [1] dlopen(s::String, flags::UInt32; throw_error::Bool)
   @ Base.Libc.Libdl ./libdl.jl:114
 [2] dlopen (repeats 2 times)
   @ ./libdl.jl:114 [inlined]
 [3] validate_libR(libR::String)
   @ Main ~/.julia/packages/RCall/dDAVd/deps/setup.jl:16
 [4] top-level scope
   @ ~/.julia/packages/RCall/dDAVd/deps/build.jl:20
 [5] include(fname::String)
   @ Base.MainInclude ./client.jl:444
 [6] top-level scope
   @ none:5

```
