### ISSUE TITLE
Error: attempt to apply non-function

### ISSUE THREAD

**Issue by schlichtanders** [JuliaInterop/RCall.jl#505]
For some julia values, the call method is not supported on R side

```R
PlutoUI = julia_eval("using PlutoUI; PlutoUI")
PlutoUI$Slider(c(1,2,3))
```
returns
```julia
REvalError: Error: attempt to apply non-function

    var"#handle_eval_stderr#31"(::Bool, ::typeof(RCall.handle_eval_stderr))@io.jl:174
    handle_eval_stderr@io.jl:168[inlined]
    reval_p(::Ptr{LangSxp}, ::Ptr{EnvSxp})@eval.jl:103
    reval_p(::Ptr{RCall.ExprSxp}, ::Ptr{EnvSxp})@eval.jl:119
    reval(::String, ::RObject{EnvSxp})@eval.jl:136
    reval(::String)@eval.jl:136
    macro expansion@[Local: 299](...)[inlined]
    top-level scope@[Local: 1](...)[inlined]
```

It would be great if the R call syntax works also here to run the julia call.

### Workaround 
```R
julia_call("PlutoUI.Slider", c(1,2,3))
```

**Comment by schlichtanders** [comment]
@simonbyrne can you comment?

**Comment by palday** [comment]
This feels like a [JuliaCall](https://github.com/Non-Contradiction/JuliaCall) issue and not an RCall issue even if the error didn't happen until it hit RCall -- I suspect something in JuliaCall's wrapping and passing isn't complete.

**Comment by schlichtanders** [comment]
I opened an issue at JuliaCall https://github.com/Non-Contradiction/JuliaCall/issues/215

**Comment by palday** [comment]
Closing this for now, but if it turns out that there is actually something we can do on the RCall side to make things easier for JuliaCall, then I'm happy to revisit.
