### ISSUE TITLE
Feature Request: Add possibility to build RCall without having R_HOME set 

### ISSUE THREAD

**Issue by schlichtanders** [JuliaInterop/RCall.jl#509]
I want to use RCall with CondaPkg, however when instantiating a project with both depenendencies, the RCall tries to build itself and cannot find an existing R, because it will be delivered by CondaPkg (concretely CondaPkg.resolve() installs all conda packages).

This is currently super tricky, because I either need an additional R installation, which takes a lot of docker resources, or somehow need to extract CondaPkg from the Manifest and install it in advance before running the full instantiation.

**Comment by frankier** [comment]
This is quite similar to your other issue https://github.com/JuliaInterop/RCall.jl/issues/513 . Please see my comments there.

**Comment by schlichtanders** [comment]
I agree, and am surprised myself to have opened two so similar issues.

This is the smaller issue in that it would already help if RCall would build successfully, even though R is not available (assuming that later on it is rebuild correctly).

But my thoughts went further and really would like to have something which needs less recompilation.
Closing this in favor of the other issue

**Comment by palday** [comment]
`ENV["R_HOME"]="_"` is the magic invocation
