### ISSUE TITLE
BUG: New R version breaks compatibility with r-juliacall. UndefVarError: `jtypExtPtrs` not defined

### ISSUE THREAD

**Issue by schlichtanders** [JuliaInterop/RCall.jl#548]
Hi there,

this really hit me. The new RCall.jl version is 1 hour old, but just got included in my setup. I am using RCall and R's juliacall together, however the new RCall version is incompatible...

It gives the following error
```
UndefVarError: `jtypExtPtrs` not defined
```
when running juliacall inside RCall.jl. Juliacall assumes that this variable exists https://github.com/search?q=repo%3ANon-Contradiction%2FJuliaCall%20jtypExtPtrs&type=code, while RCall apparently dropped it.

I guess such version compatibilities are a hard thing in general, no clue what a good solution could look like here. Like rolling support for a window of old and new versions?

**Comment by palday** [comment]
I've added in a compatibility shim in #549, but this was an internal field so it's not subject to SemVer rules. :wink:

**Comment by schlichtanders** [comment]
Thank you so much. I was thinking that r-juliacall and RCall are somehow tied together, but probably this is not the case. 
Thank you for your backwards support with deprecation!

**Comment by palday** [comment]
Nope, JuliaCall is developed independently and I don't have the ability to update it. :frowning_face:
