### ISSUE TITLE
Maintain r-juliacall?

### ISSUE THREAD

**Issue by schlichtanders** [JuliaInterop/RCall.jl#552]
Dear maintainers of RCall.jl

r-juliacall is breaking for the new julia version 1.11 which makes it uncomfortably obvious that it is currently unclear how the R-Julia interface is going to be maintained.

RCall.jl is apparently well maintained and just the other side of the coin.

I like to open the discussion, whether r-juliacall (or some new r-juliacall r package) may become maintained by the RCall maintainers, just like PythonCall includes maintenance for pyjuliacall. That would bring a lot of trust for longterm maintenance, which is key for people to seriously include Julia into their R code.

The corresponding issue at r-juliacall is this one https://github.com/Non-Contradiction/JuliaCall/issues/208

**Comment by cderv** [comment]
In the ecosystem of Julia from R package, there is also this one: https://github.com/stefan-m-lenz/JuliaConnectoR

Just want to mention it, as "new r-juliacall r package" was mentioned.

**Comment by frankier** [comment]
Looks like the move to JuliaInterop is complete now.
