### ISSUE TITLE
Feature Request: sexp for julia modules

### ISSUE THREAD

**Issue by schlichtanders** [JuliaInterop/RCall.jl#553]
currently julia modules cannot be transferred to R

It would be nice, if they did, and further support `$` for accessing names

**Comment by palday** [comment]
What is the use case? There's not anything in R that directly corresponds to a Julia module.

**Comment by schlichtanders** [comment]
actually, I learned meanwhile that this is already implemented on r-juliacall

It is handy to access julia things from R. I guess I opened this issue because I wanted to use RCall as a juliacall alternative, luckily juliacall is still going to be maintained. So I close this issue for now.
