### ISSUE TITLE
Failure to load RCall in Julia v0.4.0-rc2 compiled with LLVM 3.7.0

### ISSUE THREAD

**Issue by dmbates** [JuliaInterop/RCall.jl#70]
I'm not sure if the problem is with `RCall` or with using LLMV 3.7.0 but trying to load the RCall package results in

``` sh
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-rc2+31 (2015-09-23 01:56 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 09f248f* (2 days old release-0.4)
|__/                   |  x86_64-linux-gnu

julia> using DataFrames,DataArrays

julia> using RCall
julia: codegen.cpp:2999: llvm::Value* emit_assignment(llvm::Value*, jl_value_t*, jl_value_t*, bool, bool, jl_codectx_t*): Assertion `rval->getType() == jl_pvalue_llvmt || rval->getType() == NoopType' failed.

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f2a0b7e303d)
unknown function (ip: 0x7f2a0b7e30f2)
emit_assignment at /home/bates/git/julia/src/codegen.cpp:2999
emit_assignment at /home/bates/git/julia/src/codegen.cpp:3027
emit_function at /home/bates/git/julia/src/codegen.cpp:4681
to_function at /home/bates/git/julia/src/codegen.cpp:639
jl_compile at /home/bates/git/julia/src/codegen.cpp:808
jl_trampoline_compile_function at /home/bates/git/julia/src/builtins.c:1015
jl_apply_generic at /home/bates/git/julia/src/gf.c:1709
__init__ at /home/bates/.julia/v0.4/RCall/src/RCall.jl:117
unknown function (ip: 0x7f27f5c5f02d)
jl_eh_restore_state at /home/bates/git/julia/src/julia.h:1409
jl_eval_module_expr at /home/bates/git/julia/src/toplevel.c:210
jl_toplevel_eval_flex at /home/bates/git/julia/src/toplevel.c:423
jl_toplevel_eval_flex at /home/bates/git/julia/src/toplevel.c:573
jl_load at /home/bates/git/julia/src/toplevel.c:620
include at ./boot.jl:261
jl_apply_generic at /home/bates/git/julia/src/gf.c:1684
include_from_node1 at ./loading.jl:304
jl_apply_generic at /home/bates/git/julia/src/gf.c:1684
do_call at /home/bates/git/julia/src/interpreter.c:66
eval at /home/bates/git/julia/src/interpreter.c:213
jl_toplevel_eval_flex at /home/bates/git/julia/src/toplevel.c:544
jl_eh_restore_state at /home/bates/git/julia/src/julia.h:1409
require at ./loading.jl:243
unknown function (ip: 0x7f2a06660d39)
jl_apply_generic at /home/bates/git/julia/src/gf.c:1684
eval_import_path_ at /home/bates/git/julia/src/toplevel.c:368
jl_toplevel_eval_flex at /home/bates/git/julia/src/toplevel.c:442
jl_eh_restore_state at /home/bates/git/julia/src/julia.h:1409
eval_user_input at ./REPL.jl:63
Aborted (core dumped)
```

My versioninfo is 

```
julia> versioninfo()
Julia Version 0.4.0-rc2+31
Commit 09f248f* (2015-09-23 01:56 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.0
```

Is anyone else encountering this?

**Comment by dmbates** [comment]
I have created a `v0.4` branch that uses v0.4-specific constructions and documentation conventions.  This helps to clean up the warnings before this failure.

**Comment by dmbates** [comment]
Additional piece of information, I can load RCall with
```
julia> versioninfo()
Julia Version 0.4.0-rc2
Commit fa52609* (2015-09-18 17:51 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by simonbyrne** [comment]
Ah, I missed your branch. Hopefully I've fixed all the 0.4 deprecation stuff now, but let me know if not. I'll try to keep 0.3 supported for a while yet.

**Comment by randy3k** [comment]
I encountered the same thing on Mac with Julia 0.4.0 release.

```julia
julia> versioninfo()
Julia Version 0.4.0
Commit 0ff703b* (2015-10-08 06:20 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> using RCall
Assertion failed: (rval->getType() == jl_pvalue_llvmt || rval->getType() == NoopType), function emit_assignment, file codegen.cpp, line 2999.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
zsh: abort      julia
```

**Comment by simonbyrne** [comment]
That's not good: we should definitely be supporting LLVM 3.3. I'll see what I can find out.

**Comment by randy3k** [comment]
It seems was caused by the line
```julia
global const rJuliaCallback = RObject(makeNativeSymbol(pJuliaCallback))
```
of `RCall.jl`.

At least the package could be loaded if the line is commented.

**Comment by simonbyrne** [comment]
Hmm, this may be a weird precompilation thing.

**Comment by randy3k** [comment]
Interestingly, the package loads without errors if the line is replaced by 

```julia
    global const rJuliaCallback = (ccall((:R_MakeExternalPtrFn,libR), ExtPtrSxpPtr,
                     (Ptr{Void}, Ptr{Void}, Ptr{Void}),
                     pJuliaCallback, sexp(symbol("native symbol")), rNilValue))
    setAttrib!(rJuliaCallback, rClassSymbol, sexp("NativeSymbol"))
```

**Comment by simonbyrne** [comment]
What if you just use:
```julia
global const rJuliaCallback = makeNativeSymbol(pJuliaCallback)
```
?

**Comment by randy3k** [comment]
It doesn't work. I just note that I forgot the `RObject`.

It also works with `RObject`:
```julia
    global const rJuliaCallback = RObject(ccall((:R_MakeExternalPtrFn,libR), ExtPtrSxpPtr,
                     (Ptr{Void}, Ptr{Void}, Ptr{Void}),
                     pJuliaCallback, sexp(symbol("native symbol")), rNilValue))
    setAttrib!(rJuliaCallback, rClassSymbol, sexp("NativeSymbol"))
```

**Comment by simonbyrne** [comment]
that's bizarre

**Comment by randy3k** [comment]
I was using Julia 0.4.0 release from [staticfloat homebrew](https://github.com/staticfloat/homebrew-julia/) and I just reinstall Julia 0.4.0 from source. Now, everything works as expected.

**Comment by simonbyrne** [comment]
@staticfloat Any idea why this could be happening?

**Comment by staticfloat** [comment]
Does `RCall` load `R` into Julia's address space?  If so, my first guess is a problem with Julia's `libc` or `libstdc++` being different from `R`'s.

**Comment by dmbates** [comment]
This is an old issue.  Is it still a problem?

**Comment by simonbyrne** [comment]
I haven't tried it: I guess we will see once Julia switches 3.7.x

**Comment by randy3k** [comment]
I don't experience any problems with homebrew julia 0.4.1 now.

```
julia> versioninfo()
Julia Version 0.4.1
Commit cbe1bee* (2015-11-08 10:33 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.0.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by randy3k** [comment]
**Update**: I was wrong, I still encounter a problem with homebrew Julia v0.4.2
```
(rmbpro)-~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.2 (2015-12-06 21:47 UTC)
 _/ |\__'_|_|_|\__'_|  |  
|__/                   |  x86_64-apple-darwin15.0.0

julia> using RCall
Assertion failed: (rval->getType() == jl_pvalue_llvmt || rval->getType() == NoopType), function emit_assignment, file codegen.cpp, line 3005.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
zsh: abort      julia
```

**Comment by youngjaewoo** [comment]
Is this a related issue? I can't load RCall in my mac

julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d* (2016-01-12 21:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.2.0)
  CPU: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.test("RCall")
INFO: Testing RCall
Assertion failed: (rval->getType() == jl_pvalue_llvmt || rval->getType() == NoopType), function emit_assignment, file codegen.cpp, line 3007.

signal (6): Abort trap: 6
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
=====================================================================[ ERROR: RCall ]=====================================================================

failed process: Process(`/usr/local/Cellar/julia/0.4.3/bin/julia --check-bounds=yes --code-coverage=none --color=yes /Users/youngjaewoo/.julia/v0.4/RCall/test/runtests.jl`, ProcessSignaled(6)) [0]

==========================================================================================================================================================
ERROR: RCall had test errors
 in error at /usr/local/Cellar/julia/0.4.3/lib/julia/sys.dylib
 in test at pkg/entry.jl:803
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:22
 in cd at pkg/dir.jl:31
 in test at pkg.jl:71


Strangely, RCall loads without an error in the cluster with the below environment.

julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d (2016-01-12 21:37 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: AMD Opteron(TM) Processor 6276                 
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Bulldozer)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

Any possible fix that I can do to make RCall work in the mac?

**Comment by randy3k** [comment]
How did you install Julia on your mac? I had problems with staticfloat homebrew julia.

**Comment by youngjaewoo** [comment]
I believe I also installed julia through homebrew.

**Comment by randy3k** [comment]
You may try to use `brew cask`, or install julia from source.

**Comment by youngjaewoo** [comment]
perfect! Works great now. Thank you.

**Comment by randy3k** [comment]
@youngjaewoo I have just installed the latest version of staticfloat homebrew julia and it works now with the master branch of RCall.

```julia
julia> Pkg.test("RCall")
INFO: Testing RCall
Running tests:
 * basic.jl ...
 * conversion.jl ...
 * dataframe.jl ...
 * rstr.jl ...
INFO: RCall tests passed

julia> versioninfo()
Julia Version 0.4.3
Commit a2f713d* (2016-01-12 21:37 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.2.0)
  CPU: Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
  WORD_SIZE: 64
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

```
(rmbpro)-~$ brew info julia
staticfloat/julia/julia: stable 0.4.3 (bottled), HEAD
http://julialang.org
/usr/local/Cellar/julia/0.4.3 (676 files, 122.9M) *
  Poured from bottle
```

**Comment by uozden** [comment]
Dear @randy3k , @simonbyrne @dmbates  
I installed RCall on Julia 0.4.3, Windows 10. It is ok. But when I type `ùse RCall` it gives error, saying it is not compiled. Would you suggest any solution ? Thank you for your kind help.

**Comment by simonbyrne** [comment]
@uozden Could you copy the output?

**Comment by uozden** [comment]
Dear @simonbyrne , thank you for your kind help. The output is as follows; 

I am using: 
* Windows 10
* Julia 0.4.3 - x86_64-w64-mingw32-
* R-3.2.2 

`julia> using RCall
INFO: Precompiling module RCall...
R installation found at "C:\Program Files\R\R-3.2.2\bin"
ERROR: LoadError: error compiling __init__: could not load library ""
The specified module could not be found.
 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading C:\Users\uozden\.julia\v0.4\RCall\src\RCall.jl, in expression starting on line 475
ERROR: Failed to precompile RCall to C:\Users\uozden\.julia\lib\v0.4\RCall.ji
 in error at error.jl:21`

**Comment by uozden** [comment]
Dear @simonbyrne , This is the output of ``Pkg.test("RCall")`` 
Thank you for your help

``julia> Pkg.test("RCall")
INFO: Testing RCall
R installation found at "C:\R\R-3.2.2\bin"
ERROR: LoadError: error compiling __init__: could not load library ""
The specified module could not be found.

 in include at boot.jl:261
 in include_from_node1 at loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at client.jl:257
 in _start at client.jl:378
while loading C:\Users\....\.julia\v0.4\RCall\src\RCall.jl, in expression starting on line 475
ERROR: LoadError: Failed to precompile RCall to C:\Users\....\.julia\lib\v0.4\RCall.ji
 in error at error.jl:21
while loading C:\Users\....\.julia\v0.4\RCall\test\runtests.jl, in expression starting on line 5
====================================================[ ERROR: RCall ]====================================================

failed process: Process(`'C:\Users\.....\AppData\Local\Julia-0.4.3\bin\julia' --check-bounds=yes --code-coverage=none --color=yes 'C:\Users\.....\.julia\v0.4\RCall\test\runtests.jl'`, ProcessExited(1)) [1]

========================================================================================================================
ERROR: RCall had test errors
 in error at error.jl:21``

**Comment by simonbyrne** [comment]
Are you manually setting the `R_HOME` environment variable? If so, you shouldn't include the `bin` at the end. If not, what does
```
REG QUERY HKLM\\Software\\R-Core\\R /v InstallPath
```
at the Command Prompt give?

**Comment by uozden** [comment]
Dear @simonbyrne , thank you for your help. Yes I had set it up manually. After excluding ``bin`` with your kind help, it worked. Appreciate your time. Regards.

**Comment by robertfeldt** [comment]
I had a similar problem when installing julia 0.5.0 via homebrew on Mac OS X 10.11 but solved it like below i.e. making sure julia was uninstalled and then reinstalling from cask, as well as fresh install of RCall:

````
feldt:~$ brew uninstall julia --force
feldt:~$ brew cask uninstall julia --force
==> Removing App: '/Applications/Julia-0.5.app'
==> Removing Binary symlink: '/usr/local/bin/julia'
feldt:~$ julia
-bash: /usr/local/bin/julia: No such file or directory
feldt:~$ brew cask install julia
==> Satisfying dependencies
complete
==> Downloading https://s3.amazonaws.com/julialang/bin/osx/x64/0.5/julia-0.5.0-osx10.7+.dmg
Already downloaded: /Users/feldt/Library/Caches/Homebrew/Cask/julia--0.5.0.dmg
==> Verifying checksum for Cask julia
==> Moving App 'Julia-0.5.app' to '/Applications/Julia-0.5.app'
==> Symlinking Binary 'julia' to '/usr/local/bin/julia'
🍺  julia was successfully installed!
feldt:~$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-apple-darwin13.4.0

julia> Pkg.rm("RCall")
INFO: Removing RCall v0.5.2
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("RCall")
INFO: Installing RCall v0.5.2
INFO: Package database updated

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.test("RCall")
INFO: Testing RCall
R installation found at "/usr/local/Cellar/r/3.3.1_3/R.framework/Resources"
Running tests:
 * basic.jl ...
 * conversion.jl ...
 * dataframe.jl ...
 * rstr.jl ...
 * library.jl ...
 * repl.jl ...
INFO: RCall tests passed

julia> using RCall

julia>
```

**Comment by simonbyrne** [comment]
The original issue here appears to be resolved. Please open new issues if problems arise in future.
