### ISSUE TITLE
Automatically install R when required

### ISSUE THREAD

**Issue by simonbyrne** [JuliaInterop/RCall.jl#73]
It would be useful if we could automatically install R when no local installation is found. Here are some thoughts from having spent a morning trying and failing to get this to work:
- The R packages on linux distros are woefully out of date. The recommended way to do this is to use the CRAN repositories (e.g. see .travis.yml file). BinDeps [can't do this](https://github.com/JuliaLang/BinDeps.jl/issues/118) and probably shouldn't anyway.
- Installing the CRAN package on OS X requires administrator privileges
  - We could use the homebrew/science tap?
- CRAN doesn't provide a permalink to the latest downloads (see .travis.tml/appveyor.yml for hack workarounds)

The most promising option seems to be to use [Conda.jl](https://github.com/Luthaf/Conda.jl) (which is what PyCall.jl uses). However:
- Windows builds aren't up-to-date.
- the library (`R.dll`/`libR.dylib`/`libR.so`) is not located in a findable directory.

Getting this to work is probably going to require changing the [conda recipe](https://github.com/conda/conda-recipes/tree/master/r-base).

**Comment by phaverty** [comment]
Is this required to make testing on Travis work? I have two packages that define types and specify round-trips through related R objects and Travis fails when it can't find R.

**Comment by simonbyrne** [comment]
See https://github.com/JuliaInterop/RCall.jl/blob/master/.travis.yml

**Comment by phaverty** [comment]
Perfect, worked like a charm. I should have guessed that file already had a solution. Thanks for the help!
