### ISSUE TITLE
RCall initiation: could not find symbol R_BlankScalarString

### ISSUE THREAD

**Issue by egoecho** [JuliaInterop/RCall.jl#74]
When I run RCall in Julia 0.4.0, it have such problem. I tried Pkg.build("RCall") but it not solved. Previously RCall worked fine but the problem came after I updated anaconda (I have no idea why anaconda will lead this problem, maybe it is just coincident?).

julia> using RCall
ERROR: LoadError: InitError: cglobal: could not find symbol R_BlankScalarString in li
brary /usr/lib64/R/lib/libR.so  
 in **init** at /home/jxiong/.julia/v0.4/RCall/src/RCall.jl:71
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 in require at ./loading.jl:243
during initialization of module RCall
while loading /home/jxiong/.julia/v0.4/RCall/src/RCall.jl, in expression starting on 
line 53

**Comment by simonbyrne** [comment]
This is caused by an older version of R than is currently supported, currently we require 3.2.0 or greater. What operating system are you using?

I'll try to improve the error message.

**Comment by egoecho** [comment]
My R version is 3.1.0 (2014-04-10), will it be compatible?

**Comment by simonbyrne** [comment]
At the moment, no. Can you try commenting out [this line](https://github.com/JuliaStats/RCall.jl/blob/711da57e7e9cc3ce3c30dec8a1f521157876d9c6/src/RCall.jl#L71) and see if it works?

What OS are you using?

**Comment by egoecho** [comment]
I tried to reinstall the newest version of R (3.2.2 (2015-08-14)). When I using RCall, it crashed:

julia> using RCall

 *** caught segfault ***
address 0x54d8, cause 'memory not mapped'

Traceback:
 1: initMethodDispatch(where)
 2: fun(libname, pkgname)
 3: doTryCatch(return(expr), name, parentenv, handler)
 4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 5: tryCatchList(expr, classes, parentenv, handlers)
 6: tryCatch(fun(libname, pkgname), error = identity)
 7: runHook(".onLoad", env, package.lib, package)
 8: loadNamespace(package, c(which.lib.loc, lib.loc))
 9: doTryCatch(return(expr), name, parentenv, handler)
10: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
12: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(
call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys
.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall
, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(ms
g, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")
        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],
                 type = "b")        if (w > LONG)             prefix <- paste0(prefix
, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage
(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption
("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .In
ternal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error",
 condition = e))})                                                                  
13: try({    ns <- loadNamespace(package, c(which.lib.loc, lib.loc))    env <- attach
Namespace(ns, pos = pos, deps)})                                                    
14: library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,
     warn.conflicts = warn.conflicts, quietly = quietly)                            
15: doTryCatch(return(expr), name, parentenv, handler)
16: tryCatchOne(expr, names, parentenv, handlers[[1L]])
17: tryCatchList(expr, classes, parentenv, handlers)
18: tryCatch(library(package, lib.loc = lib.loc, character.only = TRUE,     logical.r
eturn = TRUE, warn.conflicts = warn.conflicts, quietly = quietly),     error = functi
on(e) e)                                                                            
19: require("methods", quietly = TRUE, warn.conflicts = FALSE, character.only = TRUE)
20: .OptRequireMethods()

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection:

I can enter R directly in linux and it is seems normal. Do you have idea why is it?

**Comment by randy3k** [comment]
Did you do `Pkg.build("RCall")`

**Comment by egoecho** [comment]
Yes, but it still have such problem...

**Comment by egoecho** [comment]
It seems solved after I installed R 3.2.0 (2015-04-16) instead. Many thanks!

Another question. I found that the type SEXPREC is no longer exist in RCall. Was it renamed in RCall 0.3.0?

**Comment by simonbyrne** [comment]
Yes, RCall has recently undergone a major refactor. I haven't had time to update the docs to reflect this yet.

**Comment by pearcemc** [comment]
I am having a closely related issue (on cluster so can't use package manager to install R 3.2.0). I have the following in my `~/.bash_profile` so that my 3.2.0 install is loaded when I type `R`

```
#R-settings
export R_HOME="/scratch/mcp50/paks/R-3.2.0/"
export R_BIN="/scratch/mcp50/paks/R-3.2.0/bin/"
export PATH=$R_BIN:$R_HOME:$PATH
```
Which gets me:
```
[me@login src]$ R
WARNING: ignoring environment value of R_HOME

R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
```
But when I try RCall in Julia:

```
INFO: Recompiling stale cache file /home/mcp50/.julia/lib/v0.4/RCall.ji for module RCall.
R installation found at "/scratch/mcp50/paks/R-3.2.0/"
Warning message:
In local({ : bytecode version mismatch; using eval
Error in objects(db.pos, all.names = TRUE) : 
  3 arguments passed to .Internal(ls) which requires 2
ERROR: InitError: cglobal: could not find symbol R_BlankScalarString in library libR
```
I've tried commenting out statements to do with `BlankScalarString` in `constants.jl` but the message just switches to a similar error for `R_BaseSymbol`.

**Comment by simonbyrne** [comment]
Hopefully this should now give better error messages.
